import type { FightingStyleSkillDefinition } from '../types';

export const FIGHTING_STYLE_SKILLS: readonly FightingStyleSkillDefinition[] = [
  {
    "id": "combat-z",
    "styleId": "combat",
    "key": "Z",
    "name": "Quick Tackle",
    "version": "base",
    "mastery": 1,
    "cooldown": 7.5,
    "energy": 15,
    "breaksInstinct": false,
    "description": "The user dashes forward, tackling into any enemies nearby, knocking them back quite far, while leaving behind a whirlwind of air from the swiftness of their attack."
  },
  {
    "id": "combat-x",
    "styleId": "combat",
    "key": "X",
    "name": "Ground Smash",
    "version": "base",
    "mastery": 20,
    "cooldown": 12,
    "energy": 25,
    "breaksInstinct": true,
    "description": "The user stomps their foot on the ground with devastating force, creating a medium shockwave that will knock away anyone within radius, leaving a huge crack on the floor and fragments of the ground tossed up in the air from the impact."
  },
  {
    "id": "dark-step-z",
    "styleId": "dark-step",
    "key": "Z",
    "name": "Flying Kick",
    "version": "base",
    "mastery": 1,
    "cooldown": 10,
    "energy": 15,
    "breaksInstinct": false,
    "description": "The user launches towards their cursor, leaving an impact."
  },
  {
    "id": "dark-step-x",
    "styleId": "dark-step",
    "key": "X",
    "name": "Breakdance",
    "version": "base",
    "mastery": 40,
    "cooldown": 15,
    "energy": 25,
    "breaksInstinct": false,
    "description": "The user handstands, starts spinning, attacks everything around them using their legs. Upon contact with an enemy, the user will deal damage and stun the enemy for the duration of the move. The user is unable to move during this."
  },
  {
    "id": "dark-step-c",
    "styleId": "dark-step",
    "key": "C",
    "name": "Barrage",
    "version": "base",
    "mastery": 80,
    "cooldown": 20,
    "energy": 55,
    "breaksInstinct": false,
    "description": "The user releases a barrage of kicks towards their cursor. The duration of this move will be increased if the key is held down. If the user is hit during this move, the move is canceled."
  },
  {
    "id": "dark-step-v",
    "styleId": "dark-step",
    "key": "V",
    "name": "Overheat",
    "version": "base",
    "mastery": 150,
    "cooldown": 90,
    "energy": 100,
    "breaksInstinct": false,
    "description": "The user spins really fast and sets both of their legs on fire, increasing Dark Step's damage by ~22% for 60 seconds."
  },
  {
    "id": "electric-z",
    "styleId": "electric",
    "key": "Z",
    "name": "Stomp",
    "version": "base",
    "mastery": 50,
    "cooldown": 6,
    "energy": 20,
    "breaksInstinct": false,
    "description": "The user leaps into the air. They then fill their hand with electricity and linger in the air for a short second. The user then slams down into the ground, creating a small explosion of lightning. This move is similar to Dark Step’s Z move. This can be aimed by holding a direction key on startup (i.e. forward, backward, left, right etc)."
  },
  {
    "id": "electric-x",
    "styleId": "electric",
    "key": "X",
    "name": "Electrical Tackle",
    "version": "base",
    "mastery": 100,
    "cooldown": 10,
    "energy": 30,
    "breaksInstinct": false,
    "description": "The user dashes forward where the cursor points, doing medium damage. Used primarily for dashing forward mid-air."
  },
  {
    "id": "electric-c",
    "styleId": "electric",
    "key": "C",
    "name": "Electrical Floor",
    "version": "base",
    "mastery": 200,
    "cooldown": 15,
    "energy": 60,
    "breaksInstinct": false,
    "description": "The user slams their fists in the ground, infusing the ground in front of them with electric rays for a few moments, doing AoE and stun."
  },
  {
    "id": "water-kung-fu-z",
    "styleId": "water-kung-fu",
    "key": "Z",
    "name": "Steam-Charged Fist",
    "version": "base",
    "mastery": 70,
    "cooldown": 6,
    "energy": null,
    "breaksInstinct": false,
    "description": "The user fires a blue ring that releases steam, inflicting knockback."
  },
  {
    "id": "water-kung-fu-x",
    "styleId": "water-kung-fu",
    "key": "X",
    "name": "Deadly Shower",
    "version": "base",
    "mastery": 130,
    "cooldown": 10,
    "energy": null,
    "breaksInstinct": false,
    "description": "The user shoots many fast projectiles out of their hands; this move deals decent damage. (Requires aim to be used effectively.)"
  },
  {
    "id": "water-kung-fu-c",
    "styleId": "water-kung-fu",
    "key": "C",
    "name": "Heavy Water Punch",
    "version": "base",
    "mastery": 250,
    "cooldown": 15,
    "energy": null,
    "breaksInstinct": false,
    "description": "The user charges water and lunges a powerful punch in the direction of the cursor, dealing high knockback. Can be used for movement."
  },
  {
    "id": "death-step-z",
    "styleId": "death-step",
    "key": "Z",
    "name": "Rocket Kick",
    "version": "base",
    "mastery": 100,
    "cooldown": 7.5,
    "energy": 15,
    "breaksInstinct": true,
    "description": "The user enters a stance and a whirlwind-like effect appears around the user. After releasing the move, the user dashes forward at high speed in the direction of the cursor, kicking back anyone in their way. If the user or the hit enemy makes contact with a surface, it will create an AoE dent in the surface and deals damage to anyone within it. This move can be held up to 1 second to dash further and faster."
  },
  {
    "id": "death-step-x",
    "styleId": "death-step",
    "key": "X",
    "name": "Wind Bullet",
    "version": "base",
    "mastery": 200,
    "cooldown": 10.5,
    "energy": 25,
    "breaksInstinct": true,
    "description": "The user pulls their left leg back and, upon releasing the move, kicks the air, creating a very fast wind bullet, which explodes into an AoE wind blast upon contact with a solid surface, or when it reaches its maximum distance, dealing damage and knocking back nearby enemies. The travel time of the projectile is instant. The explosion deals 25% more damage than the projectile. This move is similar to that of Godhuman's [X] move but faster, less range and can be dodged by Instinct."
  },
  {
    "id": "death-step-c",
    "styleId": "death-step",
    "key": "C",
    "name": "Vermillion Drill",
    "version": "base",
    "mastery": 300,
    "cooldown": 16.5,
    "energy": 55,
    "breaksInstinct": true,
    "description": "The user releases a barrage of kicks in a drill-like fashion towards their cursor, stunning anyone caught in the attack, and ends with a powerful downward axe kick if an enemy is caught in the barrage. The duration of this move will be increased if the key is held down. This move can be held for 3 seconds. If the user is on the ground, they will jump up upon starting this move."
  },
  {
    "id": "death-step-v",
    "styleId": "death-step",
    "key": "V",
    "name": "Maximum Overheat",
    "version": "base",
    "mastery": 400,
    "cooldown": 90,
    "energy": 100,
    "breaksInstinct": true,
    "description": "The user sets their legs on fire and creates a small explosion around their legs, damaging anyone near them. While active, this move increases Death Step's damage by ~15% for around 60 seconds. Additionally, all Death Step attacks leave fire on the ground that deals tick damage to enemies inside of it, lasting for 4 seconds. This move has a cooldown of 90 seconds."
  },
  {
    "id": "electric-claw-z",
    "styleId": "electric-claw",
    "key": "Z",
    "name": "Electric Rampage",
    "version": "base",
    "mastery": 110,
    "cooldown": 8,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user rapidly slashes using their claws (which lasts longer if held), stunning the enemy, and then dashing forward, creating electric sparks, which also deal damage. This ability also causes the user to dash farther if held."
  },
  {
    "id": "electric-claw-x",
    "styleId": "electric-claw",
    "key": "X",
    "name": "Lightning Thrust",
    "version": "base",
    "mastery": 220,
    "cooldown": 11,
    "energy": 40,
    "breaksInstinct": true,
    "description": "The user dashes forward where the cursor points. If the player touches the enemy, the player will push the enemy like a spear and then the player will make an electric explosion that deals high damage, as well as leaving the ground scorched with a blue electric pattern. After holding this skill for 1 second, a sound similar to Lightning's old [F] move regenerating will play. After releasing the attack, the distance traveled will be twice as far as just pressing the button. (This does not give any effect on the damage.)"
  },
  {
    "id": "electric-claw-c",
    "styleId": "electric-claw",
    "key": "C",
    "name": "Thunderclap and Flash",
    "version": "base",
    "mastery": 330,
    "cooldown": 17,
    "energy": 75,
    "breaksInstinct": true,
    "description": "The user dashes forward at their target at blinding speeds six times and then smashes them onto the ground, leaving the ground scorched with a blue electric pattern and bouncing the opponent into the air, stunning them for about 0.75 seconds. This move is also amazing for opening combos. Its movements are described to be akin to lightning ripping through the air."
  },
  {
    "id": "sharkman-karate-z",
    "styleId": "sharkman-karate",
    "key": "Z",
    "name": "Twelve Water Palms",
    "version": "base",
    "mastery": 100,
    "cooldown": 7,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user summons six water bodies and rushes forward. If hit, the enemy will be caught in an onslaught of palm strikes by all six figures and the user."
  },
  {
    "id": "sharkman-karate-x",
    "styleId": "sharkman-karate",
    "key": "X",
    "name": "Pressure Vortex",
    "version": "base",
    "mastery": 200,
    "cooldown": 11,
    "energy": 40,
    "breaksInstinct": false,
    "description": "The player fires a shark made of water, which on hitting an enemy, traps the enemy in a water bubble for about 1 second, before exploding."
  },
  {
    "id": "sharkman-karate-c",
    "styleId": "sharkman-karate",
    "key": "C",
    "name": "Great Sea Spear",
    "version": "base",
    "mastery": 300,
    "cooldown": 16,
    "energy": 75,
    "breaksInstinct": true,
    "description": "The player launches a vortex of water and draws it towards their body. If hit, the vortex pulls in the enemy, followed up by a barrage of aquatic strikes and a finishing double-palm strike."
  },
  {
    "id": "dragon-breath-z",
    "styleId": "dragon-breath",
    "key": "Z",
    "name": "Dragon Rush",
    "version": "base",
    "mastery": 100,
    "cooldown": 7,
    "energy": 25,
    "breaksInstinct": false,
    "description": "The user dashes forward twice, pausing in between to change direction, while engulfed in flames, with slicing particles appearing. If landed, the user punches the opponent, before going through them. If the second dash hits as well as the first dash, the damage of the second dash is divided by 10."
  },
  {
    "id": "dragon-breath-x",
    "styleId": "dragon-breath",
    "key": "X",
    "name": "Dragon Flames",
    "version": "base",
    "mastery": 200,
    "cooldown": 10,
    "energy": 35,
    "breaksInstinct": false,
    "description": "The user fires two fire dragons from their fists, spiraling them in front of them and doing damage and knockback."
  },
  {
    "id": "dragon-breath-c",
    "styleId": "dragon-breath",
    "key": "C",
    "name": "Dragon Explosion",
    "version": "base",
    "mastery": 300,
    "cooldown": 16,
    "energy": 70,
    "breaksInstinct": false,
    "description": "The user buries their fists beneath them and creates an explosion with a huge radius that leaves small, fiery rocks sticking out of the ground."
  },
  {
    "id": "superhuman-z",
    "styleId": "superhuman",
    "key": "Z",
    "name": "Beast Owl Pounce",
    "version": "base",
    "mastery": 110,
    "cooldown": 7,
    "energy": 25,
    "breaksInstinct": true,
    "description": "The user travels a decent amount of distance in any direction (can move in different directions while using the move), and if the user collides with an enemy, they will punch the target 20+ times, dealing a good amount of damage, and knocking them back slightly with a strong punch. If the user does not hit an enemy, they will just travel a decent distance. This move does not work when used with awakened Buddha unless aimed downward at the enemy. However, it can be used with unawakened Buddha. This move doesn't break Instinct, but can be useful in draining it."
  },
  {
    "id": "superhuman-x",
    "styleId": "superhuman",
    "key": "X",
    "name": "Thunder Clap",
    "version": "base",
    "mastery": 220,
    "cooldown": null,
    "energy": null,
    "breaksInstinct": true,
    "description": "The user charges up an attack and summons a tornado (if held down, the tornado does not deal damage) and when released or used, the user stomps the ground and releases a ring of power horizontally with a thunderous boom that deals decent damage to nearby enemies. Holding the move does not increase damage or knockback. This move breaks Instinct. This move somewhat works with Buddha as the ring is off-ground but can hit enemies on the ground, although its knockback makes it very bad for grinding."
  },
  {
    "id": "superhuman-c",
    "styleId": "superhuman",
    "key": "C",
    "name": "Conqueror Gun",
    "version": "base",
    "mastery": 330,
    "cooldown": null,
    "energy": null,
    "breaksInstinct": true,
    "description": "The user dashes forward in immense speed and knocks the enemy back (great knockback and damage)."
  },
  {
    "id": "dragon-talon-z",
    "styleId": "dragon-talon",
    "key": "Z",
    "name": "Talon Lighter",
    "version": "base",
    "mastery": 125,
    "cooldown": 7.5,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user lights their hand on fire and dashes towards the cursor. If the user collides with an enemy, the user will grab them and force-light their flames that turn from orange to blue inside of the enemy, before ending the attack with a kick, knocking them away. The move can be held to increase range."
  },
  {
    "id": "dragon-talon-x",
    "styleId": "dragon-talon",
    "key": "X",
    "name": "Ember Annihilation",
    "version": "base",
    "mastery": 250,
    "cooldown": 10,
    "energy": 40,
    "breaksInstinct": true,
    "description": ""
  },
  {
    "id": "dragon-talon-c",
    "styleId": "dragon-talon",
    "key": "C",
    "name": "Infernal Vortex",
    "version": "base",
    "mastery": 350,
    "cooldown": 17,
    "energy": 75,
    "breaksInstinct": true,
    "description": "The user leaps high into the sky for a second, before descending down with immense force, dealing devastating area wide damage. The explosion deals heavy knockback to anyone within its range. Additionally, the move turns the screen orange during the attack. When upgraded, it will stun enemies that are near the range at the start of the move."
  },
  {
    "id": "godhuman-z",
    "styleId": "godhuman",
    "key": "Z",
    "name": "Soaring Beast",
    "version": "base",
    "mastery": 125,
    "cooldown": 8,
    "energy": 25,
    "breaksInstinct": true,
    "description": "The user propels themselves forward in the direction of the mouse cursor. Upon making contact with an enemy, the user unleashes a rapid flurry of punches from all directions by creating after images of the user. This barrage ends with a punch that delivers brief knockback. During the move, the user is invulnerable to attacks. Additionally, the screen momentarily darkens during the last punch."
  },
  {
    "id": "godhuman-x",
    "styleId": "godhuman",
    "key": "X",
    "name": "Heaven and Earth",
    "version": "base",
    "mastery": 250,
    "cooldown": 11,
    "energy": 35,
    "breaksInstinct": true,
    "description": "This move possesses two distinct variations:"
  },
  {
    "id": "godhuman-c",
    "styleId": "godhuman",
    "key": "C",
    "name": "Sixth Realm Gun",
    "version": "base",
    "mastery": 350,
    "cooldown": 17,
    "energy": 75,
    "breaksInstinct": true,
    "description": "This move offers two distinct variations:"
  },
  {
    "id": "sanguine-art-z",
    "styleId": "sanguine-art",
    "key": "Z",
    "name": "Bloodbane Drain",
    "version": "base",
    "mastery": 125,
    "cooldown": 8,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user propels themself towards the cursor, traveling a short-medium distance. If an enemy is in the way, the user almost immediately grabs them by their neck and unleashes bat-like creatures on them which heal the user as they deal damage, before knocking them away. If hit, this move heals 20% of the user's total health, even if the enemy dodges this attack with Instinct. If the enemy is further away in the path of the move, the user will travel around 1.6x farther than normal. This move is similar to Shadow ."
  },
  {
    "id": "sanguine-art-x",
    "styleId": "sanguine-art",
    "key": "X",
    "name": "Scarlet Tear",
    "version": "base",
    "mastery": 250,
    "cooldown": 11,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user launches six claw-like slashes towards the cursor (similar to Dragon (West)'s and Dragon's third base M1), leaving claw marks on the surrounding floor or walls in front of them. These slashes explode into a scarlet burst at the end if they collide with a solid surface. This move has greater damage if the enemy is hit by both the drag and the explosion when used from a certain distance."
  },
  {
    "id": "sanguine-art-c",
    "styleId": "sanguine-art",
    "key": "C",
    "name": "Devourer of Worlds",
    "version": "base",
    "mastery": 350,
    "cooldown": 18,
    "energy": 75,
    "breaksInstinct": true,
    "description": ""
  }
] as const;

export const FIGHTING_STYLE_SKILL_BY_ID: Readonly<Record<string, FightingStyleSkillDefinition>> = Object.fromEntries(FIGHTING_STYLE_SKILLS.map((s) => [s.id, s]));
