import type { QuestDefinition } from './QuestData';

export const QUEST_DEFINITIONS: readonly QuestDefinition[] = [
  {
    id: 'starter-crabs',
    name: 'กวาดล้างปูทะเล',
    description: 'กำจัดปูทะเลดุ 5 ตัวรอบชายหาดฝึกฝน',
    minimumLevel: 1,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'crab', requiredAmount: 5 }],
    rewards: { playerExp: 120, coins: 60, masteryBonus: 15 },
  },
  {
    id: 'starter-pirates',
    name: 'โจรสลัดเร่ร่อน',
    description: 'หยุดโจรสลัดเร่ร่อน 5 คนที่คุกคามหมู่บ้าน',
    minimumLevel: 3,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'grunt', requiredAmount: 5 }],
    rewards: { playerExp: 240, coins: 120, masteryBonus: 25 },
  },
  {
    id: 'east-hill-captain',
    name: 'กัปตันแห่งเนินตะวันออก',
    description: 'โค่นกัปตันหนวดดำที่เนินฝั่งตะวันออก',
    minimumLevel: 7,
    repeatable: true,
    objectives: [{ type: 'boss', targetId: 'boss', requiredAmount: 1 }],
    rewards: { playerExp: 600, coins: 350, masteryBonus: 80 },
  },
  {
    id: 'mist-jungle-bandits',
    name: 'เงาโจรในพงไพร',
    description: 'กำจัดโจรป่าพงไพร 6 คนที่คุมเส้นทางใต้ของเกาะ',
    minimumLevel: 15,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'jungle-bandit', requiredAmount: 6 }],
    rewards: { playerExp: 720, coins: 420, masteryBonus: 90 },
  },
  {
    id: 'ancient-guardians',
    name: 'ผู้พิทักษ์ที่ตื่นขึ้น',
    description: 'ปราบผู้พิทักษ์ศิลา 5 ตนรอบซากวิหารโบราณ',
    minimumLevel: 20,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'ruin-guardian', requiredAmount: 5 }],
    rewards: { playerExp: 1100, coins: 650, masteryBonus: 140 },
  },
  {
    id: 'mist-jungle-cleansing',
    name: 'กวาดล้างเส้นทางวิหาร',
    description: 'เปิดเส้นทางด้วยการกำจัดโจรป่าและผู้พิทักษ์ศิลา',
    minimumLevel: 23,
    repeatable: true,
    objectives: [
      { type: 'kill', targetId: 'jungle-bandit', requiredAmount: 3 },
      { type: 'kill', targetId: 'ruin-guardian', requiredAmount: 3 },
    ],
    rewards: { playerExp: 1450, coins: 850, masteryBonus: 180 },
  },
  {
    id: 'venom-ape-hunt',
    name: 'ราชาแห่งม่านหมอก',
    description: 'โค่นวานรพิษโบราณที่เฝ้าถ้ำทางเหนือ',
    minimumLevel: 25,
    repeatable: true,
    objectives: [{ type: 'boss', targetId: 'venom-ape-boss', requiredAmount: 1 }],
    rewards: { playerExp: 2600, coins: 1600, masteryBonus: 320 },
  },
  {
    id: 'sunscar-scorpions',
    name: 'เงาใต้ผืนทราย',
    description: 'กำจัดแมงป่องเนินทราย 7 ตัวรอบโอเอซิสและเนินตะวันออก',
    minimumLevel: 31,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'dune-scorpion', requiredAmount: 7 }],
    rewards: { playerExp: 1850, coins: 1050, masteryBonus: 220 },
  },
  {
    id: 'sunscar-raider-route',
    name: 'ชิงเส้นทางคาราวานคืน',
    description: 'ปราบโจรคาราวาน 6 คนที่ยึดเส้นทางตะวันตก',
    minimumLevel: 34,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'desert-raider', requiredAmount: 6 }],
    rewards: { playerExp: 2300, coins: 1350, masteryBonus: 280 },
  },
  {
    id: 'sunscar-sand-golems',
    name: 'เสียงคำรามจากเหมือง',
    description: 'ทำลายโกเลมศิลาทราย 5 ตนในเหมืองตะวันออก',
    minimumLevel: 40,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'sand-golem', requiredAmount: 5 }],
    rewards: { playerExp: 3100, coins: 1900, masteryBonus: 360 },
  },
  {
    id: 'sun-guardian-awakens',
    name: 'ผู้พิทักษ์แห่งดวงอาทิตย์',
    description: 'โค่นผู้พิทักษ์สุริยะหน้าพีระมิดทางเหนือ',
    minimumLevel: 45,
    repeatable: true,
    objectives: [{ type: 'boss', targetId: 'sun-guardian-boss', requiredAmount: 1 }],
    rewards: { playerExp: 5200, coins: 3200, masteryBonus: 650 },
  },
  { id: 'azure-frost-crawlers', name: 'เงาบนผืนน้ำแข็ง', description: 'กำจัดแมงมุมน้ำแข็ง 7 ตัวรอบทะเลสาบและชายหิมะใต้', minimumLevel: 51, repeatable: true, objectives: [{ type: 'kill', targetId: 'frost-crawler', requiredAmount: 7 }], rewards: { playerExp: 3900, coins: 2400, masteryBonus: 430 } },
  { id: 'azure-frost-raiders', name: 'ชิงเส้นทางหิมะคืน', description: 'ปราบโจรน้ำแข็ง 6 คนที่คุมเส้นทางตะวันตก', minimumLevel: 55, repeatable: true, objectives: [{ type: 'kill', targetId: 'frost-raider', requiredAmount: 6 }], rewards: { playerExp: 4600, coins: 2900, masteryBonus: 520 } },
  { id: 'azure-crystal-golems', name: 'หัวใจแห่งเหมืองคริสตัล', description: 'ทำลายโกเลมคริสตัลคราม 5 ตนในเหมืองทางเหนือ', minimumLevel: 61, repeatable: true, objectives: [{ type: 'kill', targetId: 'crystal-golem', requiredAmount: 5 }], rewards: { playerExp: 5900, coins: 3800, masteryBonus: 650 } },
  { id: 'ancient-frost-king', name: 'บัลลังก์เหมันต์นิรันดร์', description: 'โค่นราชันน้ำแข็งโบราณที่ป้อมเหนือสุด', minimumLevel: 65, repeatable: true, objectives: [{ type: 'boss', targetId: 'frost-king-boss', requiredAmount: 1 }], rewards: { playerExp: 8400, coins: 5400, masteryBonus: 900 } },
  {
    id: 'trade-fish-to-desert',
    name: 'ส่งอาหารสู่เกาะทอผ้า',
    description: 'ซื้อปลาสดที่เกาะใบไม้ แล่นเรือไปขายที่เกาะทอผ้า 5 ชิ้น',
    minimumLevel: 5,
    repeatable: true,
    objectives: [{
      type: 'deliver',
      targetId: 'fresh-fish',
      requiredAmount: 5,
      islandId: 'sunscar-desert',
    }],
    rewards: { playerExp: 280, coins: 200, masteryBonus: 20 },
  },
  {
    id: 'trade-wood-to-mine',
    name: 'ส่งไม้สู่เกาะเหมือง',
    description: 'ซื้อไม้ที่เกาะใบไม้ แล่นเรือไปขายที่เกาะเหมือง 8 ชิ้น',
    minimumLevel: 8,
    repeatable: true,
    objectives: [{
      type: 'deliver',
      targetId: 'hardwood',
      requiredAmount: 8,
      islandId: 'mist-jungle',
    }],
    rewards: { playerExp: 420, coins: 320, masteryBonus: 35 },
  },
  {
    id: 'trade-iron-to-desert',
    name: 'เส้นทางเหล็กสู่ทอผ้า',
    description: 'ซื้อแร่เหล็กที่เกาะเหมือง แล้วขายที่เกาะทอผ้า 6 ชิ้น',
    minimumLevel: 18,
    repeatable: true,
    objectives: [{
      type: 'deliver',
      targetId: 'iron-ore',
      requiredAmount: 6,
      islandId: 'sunscar-desert',
    }],
    rewards: { playerExp: 680, coins: 480, masteryBonus: 55 },
  },
  {
    id: 'trade-silk-route',
    name: 'เส้นทางผ้าไปอู่เรือ',
    description: 'ซื้อผ้าไหมที่เกาะทอผ้า แล้วขายที่อู่เรือ (เกาะเริ่มต้น) 6 ชิ้น',
    minimumLevel: 12,
    repeatable: true,
    objectives: [{
      type: 'deliver',
      targetId: 'sun-silk',
      requiredAmount: 6,
      islandId: 'starter-island',
    }],
    rewards: { playerExp: 520, coins: 380, masteryBonus: 45 },
  },
  {
    id: 'trade-dried-fish-to-mine',
    name: 'ส่งปลาแห้งสู่เหมือง',
    description: 'ขายปลาแห้ง 6 ชิ้นที่เกาะเหมือง',
    minimumLevel: 6,
    repeatable: true,
    objectives: [{
      type: 'deliver',
      targetId: 'dried-fish',
      requiredAmount: 6,
      islandId: 'mist-jungle',
    }],
    rewards: { playerExp: 320, coins: 240, masteryBonus: 25 },
  },
  {
    id: 'trade-tools-to-leaf',
    name: 'ส่งเครื่องมือสู่เกาะใบไม้',
    description: 'ขายเครื่องมือช่าง 4 ชิ้นที่เกาะเริ่มต้น',
    minimumLevel: 10,
    repeatable: true,
    objectives: [{
      type: 'deliver',
      targetId: 'tools',
      requiredAmount: 4,
      islandId: 'starter-island',
    }],
    rewards: { playerExp: 480, coins: 360, masteryBonus: 40 },
  },
  {
    id: 'trade-rope-to-shipyard',
    name: 'ส่งเชือกสู่อู่เรือ',
    description: 'ขายเชือกเดินเรือ 6 ชิ้นที่อู่เรือ (เกาะเริ่มต้น)',
    minimumLevel: 14,
    repeatable: true,
    objectives: [{
      type: 'deliver',
      targetId: 'rope',
      requiredAmount: 6,
      islandId: 'starter-island',
    }],
    rewards: { playerExp: 560, coins: 400, masteryBonus: 48 },
  },
  {
    id: 'trade-ingot-route',
    name: 'เส้นทางแท่งเหล็ก',
    description: 'ขายแท่งเหล็ก 5 ชิ้นที่เกาะเริ่มต้น',
    minimumLevel: 16,
    repeatable: true,
    objectives: [{
      type: 'deliver',
      targetId: 'iron-ingot',
      requiredAmount: 5,
      islandId: 'starter-island',
    }],
    rewards: { playerExp: 620, coins: 440, masteryBonus: 52 },
  },
  {
    id: 'trade-shipyard-supply',
    name: 'ช่วยอู่เรือผลิตชุดซ่อม',
    description: 'ส่งวัตถุดิบให้อู่เรือ: ไม้ 6, แท่งเหล็ก 3, เชือก 3',
    minimumLevel: 20,
    repeatable: true,
    objectives: [
      { type: 'deliver', targetId: 'hardwood', requiredAmount: 6, islandId: 'starter-island' },
      { type: 'deliver', targetId: 'iron-ingot', requiredAmount: 3, islandId: 'starter-island' },
      { type: 'deliver', targetId: 'rope', requiredAmount: 3, islandId: 'starter-island' },
    ],
    rewards: { playerExp: 900, coins: 650, masteryBonus: 70 },
  },
  {
    id: 'trade-luxury-market',
    name: 'ตลาดผ้าหรู',
    description: 'ขายผ้าหรู 3 ชิ้นที่เกาะทอผ้า',
    minimumLevel: 22,
    repeatable: true,
    objectives: [{
      type: 'deliver',
      targetId: 'luxury-cloth',
      requiredAmount: 3,
      islandId: 'sunscar-desert',
    }],
    rewards: { playerExp: 780, coins: 580, masteryBonus: 65 },
  },
];

export const QUESTS_BY_ID = new Map(QUEST_DEFINITIONS.map((quest) => [quest.id, quest]));
