import type { QuestDefinition } from './QuestData';

export const QUEST_DEFINITIONS: readonly QuestDefinition[] = [
  {
    id: 'starter-crabs',
    name: 'กวาดล้างปูทะเล',
    description: 'กำจัดปูทะเลดุ 5 ตัวรอบชายหาดฝึกฝน',
    minimumLevel: 1,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'crab', requiredAmount: 5 }],
    rewards: { playerExp: 120, coins: 60, masteryBonus: 15 },
  },
  {
    id: 'starter-pirates',
    name: 'โจรสลัดเร่ร่อน',
    description: 'หยุดโจรสลัดเร่ร่อน 5 คนที่คุกคามหมู่บ้าน',
    minimumLevel: 3,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'grunt', requiredAmount: 5 }],
    rewards: { playerExp: 240, coins: 120, masteryBonus: 25 },
  },
  {
    id: 'east-hill-captain',
    name: 'กัปตันแห่งเนินตะวันออก',
    description: 'โค่นกัปตันหนวดดำที่เนินฝั่งตะวันออก',
    minimumLevel: 7,
    repeatable: true,
    objectives: [{ type: 'boss', targetId: 'boss', requiredAmount: 1 }],
    rewards: { playerExp: 600, coins: 350, masteryBonus: 80 },
  },
  {
    id: 'mist-jungle-bandits',
    name: 'เงาโจรในพงไพร',
    description: 'กำจัดโจรป่าพงไพร 6 คนที่คุมเส้นทางใต้ของเกาะ',
    minimumLevel: 15,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'jungle-bandit', requiredAmount: 6 }],
    rewards: { playerExp: 720, coins: 420, masteryBonus: 90 },
  },
  {
    id: 'ancient-guardians',
    name: 'ผู้พิทักษ์ที่ตื่นขึ้น',
    description: 'ปราบผู้พิทักษ์ศิลา 5 ตนรอบซากวิหารโบราณ',
    minimumLevel: 20,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'ruin-guardian', requiredAmount: 5 }],
    rewards: { playerExp: 1100, coins: 650, masteryBonus: 140 },
  },
  {
    id: 'mist-jungle-cleansing',
    name: 'กวาดล้างเส้นทางวิหาร',
    description: 'เปิดเส้นทางด้วยการกำจัดโจรป่าและผู้พิทักษ์ศิลา',
    minimumLevel: 23,
    repeatable: true,
    objectives: [
      { type: 'kill', targetId: 'jungle-bandit', requiredAmount: 3 },
      { type: 'kill', targetId: 'ruin-guardian', requiredAmount: 3 },
    ],
    rewards: { playerExp: 1450, coins: 850, masteryBonus: 180 },
  },
  {
    id: 'venom-ape-hunt',
    name: 'ราชาแห่งม่านหมอก',
    description: 'โค่นวานรพิษโบราณที่เฝ้าถ้ำทางเหนือ',
    minimumLevel: 25,
    repeatable: true,
    objectives: [{ type: 'boss', targetId: 'venom-ape-boss', requiredAmount: 1 }],
    rewards: { playerExp: 2600, coins: 1600, masteryBonus: 320 },
  },
  {
    id: 'sunscar-scorpions',
    name: 'เงาใต้ผืนทราย',
    description: 'กำจัดแมงป่องเนินทราย 7 ตัวรอบโอเอซิสและเนินตะวันออก',
    minimumLevel: 31,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'dune-scorpion', requiredAmount: 7 }],
    rewards: { playerExp: 1850, coins: 1050, masteryBonus: 220 },
  },
  {
    id: 'sunscar-raider-route',
    name: 'ชิงเส้นทางคาราวานคืน',
    description: 'ปราบโจรคาราวาน 6 คนที่ยึดเส้นทางตะวันตก',
    minimumLevel: 34,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'desert-raider', requiredAmount: 6 }],
    rewards: { playerExp: 2300, coins: 1350, masteryBonus: 280 },
  },
  {
    id: 'sunscar-sand-golems',
    name: 'เสียงคำรามจากเหมือง',
    description: 'ทำลายโกเลมศิลาทราย 5 ตนในเหมืองตะวันออก',
    minimumLevel: 40,
    repeatable: true,
    objectives: [{ type: 'kill', targetId: 'sand-golem', requiredAmount: 5 }],
    rewards: { playerExp: 3100, coins: 1900, masteryBonus: 360 },
  },
  {
    id: 'sun-guardian-awakens',
    name: 'ผู้พิทักษ์แห่งดวงอาทิตย์',
    description: 'โค่นผู้พิทักษ์สุริยะหน้าพีระมิดทางเหนือ',
    minimumLevel: 45,
    repeatable: true,
    objectives: [{ type: 'boss', targetId: 'sun-guardian-boss', requiredAmount: 1 }],
    rewards: { playerExp: 5200, coins: 3200, masteryBonus: 650 },
  },
];

export const QUESTS_BY_ID = new Map(QUEST_DEFINITIONS.map((quest) => [quest.id, quest]));
