import type { CommodityDefinition } from '../types';

/** สินค้าเทรดระหว่างเกาะ — แยกจากอาวุธ/ผลไม้ (equipment) */
export const TRADE_COMMODITIES: readonly CommodityDefinition[] = [
  {
    id: 'fresh-fish',
    name: 'Fresh Fish',
    nameTh: 'ปลาสด',
    category: 'food',
    basePrice: 45,
    weight: 2,
    icon: '🐟',
    description: 'ปลาจากชายฝั่งเกาะเริ่มต้น',
  },
  {
    id: 'dried-fish',
    name: 'Dried Fish',
    nameTh: 'ปลาแห้ง',
    category: 'food',
    basePrice: 68,
    weight: 1,
    icon: '🐠',
    description: 'ปลาแห้ง — เก็บได้นาน เหมาะเดินทางไกล',
  },
  {
    id: 'hardwood',
    name: 'Hardwood',
    nameTh: 'ไม้เนื้อแข็ง',
    category: 'material',
    basePrice: 60,
    weight: 4,
    icon: '🪵',
    description: 'ไม้จากป่าเกาะเริ่มต้น',
  },
  {
    id: 'sailcloth',
    name: 'Ship Parts',
    nameTh: 'ชิ้นส่วนเรือ',
    category: 'supply',
    basePrice: 240,
    weight: 6,
    icon: '⚓',
    description: 'ชิ้นส่วนเรือจากอู่ — ไม้ แท่งเหล็ก และเชือก',
  },
  {
    id: 'iron-ore',
    name: 'Iron Ore',
    nameTh: 'แร่เหล็ก',
    category: 'material',
    basePrice: 110,
    weight: 5,
    icon: '⛏️',
    description: 'แร่เหล็กจากเหมืองพงไพรหมอก',
  },
  {
    id: 'iron-ingot',
    name: 'Iron Ingot',
    nameTh: 'แท่งเหล็ก',
    category: 'material',
    basePrice: 165,
    weight: 4,
    icon: '🔩',
    description: 'แท่งเหล็กหลอมจากแร่ — วัตถุดิบกลางน้ำ',
  },
  {
    id: 'tools',
    name: 'Craft Tools',
    nameTh: 'เครื่องมือช่าง',
    category: 'supply',
    basePrice: 320,
    weight: 3,
    icon: '🔧',
    description: 'เครื่องมือช่าง — เพิ่มประสิทธิภาพการผลิต',
  },
  {
    id: 'healing-herb',
    name: 'Healing Herb',
    nameTh: 'สมุนไพร',
    category: 'material',
    basePrice: 95,
    weight: 1,
    icon: '🌿',
    description: 'สมุนไพรจากป่าพงไพรหมอก',
  },
  {
    id: 'herbal-medicine',
    name: 'Herbal Medicine',
    nameTh: 'ยาสมุนไพร',
    category: 'supply',
    basePrice: 180,
    weight: 1,
    icon: '💊',
    description: 'ยาสมุนไพรแปรรูป — ฟื้นพลังและรักษาแรงงาน',
  },
  {
    id: 'ancient-relic',
    name: 'Ancient Relic',
    nameTh: 'ซากโบราณ',
    category: 'relic',
    basePrice: 350,
    weight: 5,
    icon: '🏺',
    description: 'ของโบราณจากวิหารในป่า',
  },
  {
    id: 'mist-spice',
    name: 'Mist Spice',
    nameTh: 'เครื่องเทศหมอก',
    category: 'luxury',
    basePrice: 200,
    weight: 1,
    icon: '🫙',
    description: 'เครื่องเทศหอมจากเกาะพงไพร',
  },
  {
    id: 'desert-salt',
    name: 'Desert Salt',
    nameTh: 'เกลือทะเลทราย',
    category: 'material',
    basePrice: 110,
    weight: 3,
    icon: '🧂',
    description: 'เกลือบริสุทธิ์จากทะเลทราย',
  },
  {
    id: 'sun-silk',
    name: 'Sun Silk',
    nameTh: 'ผ้าไหมสุริยะ',
    category: 'luxury',
    basePrice: 280,
    weight: 2,
    icon: '🧣',
    description: 'ผ้าไหมจากคาราวานทะเลทราย',
  },
  {
    id: 'rope',
    name: 'Sail Rope',
    nameTh: 'เชือกเดินเรือ',
    category: 'supply',
    basePrice: 140,
    weight: 2,
    icon: '🪢',
    description: 'เชือกจากผ้าไหม — ใช้ผลิตเรือและหีบสินค้า',
  },
  {
    id: 'luxury-cloth',
    name: 'Luxury Cloth',
    nameTh: 'ผ้าหรู',
    category: 'luxury',
    basePrice: 520,
    weight: 2,
    icon: '👘',
    description: 'ผ้าหรู — ขายดีในเกาะมั่งคั่ง',
  },
  {
    id: 'repair-kit',
    name: 'Repair Kit',
    nameTh: 'ชุดซ่อมเรือ',
    category: 'supply',
    basePrice: 195,
    weight: 4,
    icon: '🛠️',
    description: 'ชุดซ่อมเรือ — ไม้ แท่งเหล็ก และเชือก',
  },
  {
    id: 'trade-crate',
    name: 'Trade Crate',
    nameTh: 'หีบสินค้า',
    category: 'supply',
    basePrice: 125,
    weight: 3,
    icon: '📦',
    description: 'หีบสินค้ามาตรฐาน — ลดการเน่าเสียของอาหาร',
  },
  {
    id: 'frost-crystal',
    name: 'Frost Crystal',
    nameTh: 'ผลึกเหมันต์',
    category: 'relic',
    basePrice: 360,
    weight: 2,
    icon: '❄️',
    description: 'ผลึกพลังเย็นจากเหมืองเกาะเหมันต์คราม — ใช้แลกเปลี่ยนกับเกาะชั้นสูง',
  },
  {
    id: 'storm-core',
    name: 'Storm Core',
    nameTh: 'แกนพายุ',
    category: 'relic',
    basePrice: 480,
    weight: 2,
    icon: '🌀',
    description: 'แกนพายุที่เก็บประจุจากยอดเกาะนภาวายุ — หายากและมีราคาสูงเมื่อขาดแคลน',
  },
  {
    id: 'volcanic-ore',
    name: 'Volcanic Ore',
    nameTh: 'แร่อัคคี',
    category: 'material',
    basePrice: 300,
    weight: 5,
    icon: '🌋',
    description: 'แร่ร้อนจากเหมืองเกาะภูผาอัคคี — วัตถุดิบสำคัญของช่างตีเหล็ก',
  },
  {
    id: 'desert-gem',
    name: 'Desert Gem',
    nameTh: 'อัญมณีทราย',
    category: 'luxury',
    basePrice: 520,
    weight: 1,
    icon: '💎',
    description: 'อัญมณีจาก mesa กลางทะเลทราย',
  },
  {
    id: 'cactus-water',
    name: 'Cactus Water',
    nameTh: 'น้ำกระบองเพชร',
    category: 'food',
    basePrice: 75,
    weight: 2,
    icon: '🌵',
    description: 'น้ำดื่มจากทะเลทราย — ขาดแคลนในเกาะอื่น',
  },
] as const;
