import type { CommodityDefinition } from '../types';

/** สินค้าเทรดระหว่างเกาะ — แยกจากอาวุธ/ผลไม้ (equipment) */
export const TRADE_COMMODITIES: readonly CommodityDefinition[] = [
  {
    id: 'fresh-fish',
    name: 'Fresh Fish',
    nameTh: 'ปลาสด',
    category: 'food',
    basePrice: 45,
    weight: 2,
    icon: '🐟',
    description: 'ปลาจากชายฝั่งเกาะเริ่มต้น',
  },
  {
    id: 'hardwood',
    name: 'Hardwood',
    nameTh: 'ไม้เนื้อแข็ง',
    category: 'material',
    basePrice: 60,
    weight: 4,
    icon: '🪵',
    description: 'ไม้จากป่าเกาะเริ่มต้น',
  },
  {
    id: 'sailcloth',
    name: 'Sailcloth',
    nameTh: 'ผ้าใบเรือ',
    category: 'supply',
    basePrice: 90,
    weight: 3,
    icon: '🧵',
    description: 'อุปกรณ์เรือพื้นฐาน',
  },
  {
    id: 'jungle-herb',
    name: 'Jungle Herb',
    nameTh: 'สมุนไพรป่า',
    category: 'material',
    basePrice: 120,
    weight: 1,
    icon: '🌿',
    description: 'สมุนไพรหายากจากพงไพรหมอก',
  },
  {
    id: 'ancient-relic',
    name: 'Ancient Relic',
    nameTh: 'ซากโบราณ',
    category: 'relic',
    basePrice: 350,
    weight: 5,
    icon: '🏺',
    description: 'ของโบราณจากวิหารในป่า',
  },
  {
    id: 'mist-spice',
    name: 'Mist Spice',
    nameTh: 'เครื่องเทศหมอก',
    category: 'luxury',
    basePrice: 200,
    weight: 1,
    icon: '🫙',
    description: 'เครื่องเทศหอมจากเกาะพงไพร',
  },
  {
    id: 'desert-salt',
    name: 'Desert Salt',
    nameTh: 'เกลือทะเลทราย',
    category: 'material',
    basePrice: 110,
    weight: 3,
    icon: '🧂',
    description: 'เกลือบริสุทธิ์จากทะเลทราย',
  },
  {
    id: 'sun-silk',
    name: 'Sun Silk',
    nameTh: 'ผ้าไหมสุริยะ',
    category: 'luxury',
    basePrice: 280,
    weight: 2,
    icon: '🧣',
    description: 'ผ้าไหมจากคาราวานทะเลทราย',
  },
  {
    id: 'desert-gem',
    name: 'Desert Gem',
    nameTh: 'อัญมณีทราย',
    category: 'luxury',
    basePrice: 520,
    weight: 1,
    icon: '💎',
    description: 'อัญมณีจาก mesa กลางทะเลทราย',
  },
  {
    id: 'cactus-water',
    name: 'Cactus Water',
    nameTh: 'น้ำกระบองเพชร',
    category: 'food',
    basePrice: 75,
    weight: 2,
    icon: '🌵',
    description: 'น้ำดื่มจากทะเลทราย — ขาดแคลนในเกาะอื่น',
  },
] as const;
