import type { IslandMarketDefinition } from '../types';

/**
 * ตลาด Living Trade — ราคาจาก Economic CA (ไม่ใช้ multiplier คงที่)
 */
export const ISLAND_MARKETS: readonly IslandMarketDefinition[] = [
  {
    id: 'starter-market',
    islandId: 'starter-island',
    name: 'Leaf Island Market',
    nameTh: 'ตลาดเกาะใบไม้',
    harborDockId: 'starter-harbor',
    entries: [
      { commodityId: 'fresh-fish', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'dried-fish', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'hardwood', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'trade-crate', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'iron-ingot', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'tools', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'sun-silk', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'rope', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
    ],
  },
  {
    id: 'starter-shipyard-market',
    islandId: 'starter-island',
    name: 'Shipyard Exchange',
    nameTh: 'ตลาดอู่เรือ',
    harborDockId: 'starter-harbor',
    entries: [
      { commodityId: 'sailcloth', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'repair-kit', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'trade-crate', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'tools', role: 'neutral', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'hardwood', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'iron-ingot', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'rope', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'dried-fish', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'sun-silk', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
    ],
  },
  {
    id: 'mist-jungle-market',
    islandId: 'mist-jungle',
    name: 'Mine Island Exchange',
    nameTh: 'ตลาดเกาะเหมือง',
    harborDockId: 'mist-jungle-harbor',
    entries: [
      { commodityId: 'iron-ore', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'iron-ingot', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'healing-herb', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'herbal-medicine', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'tools', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'fresh-fish', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'dried-fish', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'hardwood', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'sun-silk', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
    ],
  },
  {
    id: 'sunscar-desert-market',
    islandId: 'sunscar-desert',
    name: 'Cloth Island Bazaar',
    nameTh: 'ตลาดเกาะทอผ้า',
    harborDockId: 'sunscar-desert-harbor',
    entries: [
      { commodityId: 'sun-silk', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'rope', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'luxury-cloth', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'fresh-fish', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'dried-fish', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'hardwood', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'iron-ingot', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'tools', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'sailcloth', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'repair-kit', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
    ],
  },
  {
    id: 'azure-frost-market',
    islandId: 'azure-frost',
    name: 'Frost Harbor Exchange',
    nameTh: 'ตลาดท่าเหมันต์',
    harborDockId: 'azure-frost-harbor',
    entries: [
      { commodityId: 'frost-crystal', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'fresh-fish', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 40 },
      { commodityId: 'dried-fish', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 50 },
      { commodityId: 'hardwood', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 45 },
      { commodityId: 'iron-ingot', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 35 },
      { commodityId: 'tools', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 30 },
      { commodityId: 'herbal-medicine', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 30 },
      { commodityId: 'sun-silk', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 30 },
      { commodityId: 'storm-core', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 24 },
      { commodityId: 'volcanic-ore', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 24 },
    ],
  },
  {
    id: 'tempest-sky-market',
    islandId: 'tempest-sky',
    name: 'Tempest Sky Exchange',
    nameTh: 'ตลาดเกาะนภาวายุ',
    harborDockId: 'tempest-sky-harbor',
    entries: [
      { commodityId: 'storm-core', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'fresh-fish', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 35 },
      { commodityId: 'dried-fish', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 45 },
      { commodityId: 'hardwood', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 40 },
      { commodityId: 'iron-ingot', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 32 },
      { commodityId: 'tools', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 30 },
      { commodityId: 'sun-silk', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 30 },
      { commodityId: 'rope', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 32 },
      { commodityId: 'frost-crystal', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 24 },
      { commodityId: 'volcanic-ore', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 22 },
      { commodityId: 'sailcloth', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 28 },
    ],
  },
  {
    id: 'ember-volcano-market',
    islandId: 'ember-volcano',
    name: 'Ember Volcano Exchange',
    nameTh: 'ตลาดเกาะภูผาอัคคี',
    harborDockId: 'ember-volcano-harbor',
    entries: [
      { commodityId: 'volcanic-ore', role: 'export', buyMultiplier: 1, sellMultiplier: 1, stockLimit: -1 },
      { commodityId: 'fresh-fish', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 38 },
      { commodityId: 'dried-fish', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 46 },
      { commodityId: 'hardwood', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 40 },
      { commodityId: 'iron-ingot', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 34 },
      { commodityId: 'tools', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 30 },
      { commodityId: 'sun-silk', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 30 },
      { commodityId: 'rope', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 30 },
      { commodityId: 'frost-crystal', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 24 },
      { commodityId: 'storm-core', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 22 },
      { commodityId: 'repair-kit', role: 'import', buyMultiplier: 1, sellMultiplier: 1, stockLimit: 28 },
    ],
  },
] as const;
