import type { TradeRouteDefinition } from '../types';

/** เส้นทางเทรดระหว่างท่าเรือ — ใช้กับระบบเรือ */
export const TRADE_ROUTES: readonly TradeRouteDefinition[] = [
  {
    id: 'starter-to-mist',
    name: 'Starter → Mist Jungle',
    nameTh: 'เกาะเริ่มต้น → พงไพรหมอก',
    fromIslandId: 'starter-island',
    toIslandId: 'mist-jungle',
    fromDockId: 'starter-harbor',
    toDockId: 'mist-jungle-harbor',
    distance: 175,
    recommendedCommodityIds: ['fresh-fish', 'hardwood'],
    notes: 'ซื้อปลา/ไม้ถูกที่เกาะแรก ขายแพงที่ป่า',
  },
  {
    id: 'mist-to-starter',
    name: 'Mist Jungle → Starter',
    nameTh: 'พงไพรหมอก → เกาะเริ่มต้น',
    fromIslandId: 'mist-jungle',
    toIslandId: 'starter-island',
    fromDockId: 'mist-jungle-harbor',
    toDockId: 'starter-harbor',
    distance: 175,
    recommendedCommodityIds: ['jungle-herb', 'mist-spice', 'ancient-relic'],
    notes: 'ส่งออกสมุนไพร/เครื่องเทศกลับหมู่บ้าน',
  },
  {
    id: 'starter-to-sunscar',
    name: 'Starter → Sunscar Desert',
    nameTh: 'เกาะเริ่มต้น → ทะเลทรายสุริยะ',
    fromIslandId: 'starter-island',
    toIslandId: 'sunscar-desert',
    fromDockId: 'starter-harbor',
    toDockId: 'sunscar-desert-harbor',
    distance: 165,
    recommendedCommodityIds: ['fresh-fish', 'hardwood', 'sailcloth'],
    notes: 'ทะเลทรายต้องการอาหารและไม้',
  },
  {
    id: 'sunscar-to-starter',
    name: 'Sunscar Desert → Starter',
    nameTh: 'ทะเลทรายสุริยะ → เกาะเริ่มต้น',
    fromIslandId: 'sunscar-desert',
    toIslandId: 'starter-island',
    fromDockId: 'sunscar-desert-harbor',
    toDockId: 'starter-harbor',
    distance: 165,
    recommendedCommodityIds: ['sun-silk', 'desert-gem', 'desert-salt'],
    notes: 'ของหรูจากทะเลทรายขายดีที่หมู่บ้าน',
  },
  {
    id: 'mist-to-sunscar',
    name: 'Mist Jungle → Sunscar Desert',
    nameTh: 'พงไพรหมอก → ทะเลทรายสุริยะ',
    fromIslandId: 'mist-jungle',
    toIslandId: 'sunscar-desert',
    fromDockId: 'mist-jungle-harbor',
    toDockId: 'sunscar-desert-harbor',
    distance: 170,
    recommendedCommodityIds: ['jungle-herb', 'ancient-relic'],
    notes: 'เส้นทาง arbitrage กลาง — สมุนไพร→ทะเลทราย, เกลือ→ป่า',
  },
  {
    id: 'sunscar-to-mist',
    name: 'Sunscar Desert → Mist Jungle',
    nameTh: 'ทะเลทรายสุริยะ → พงไพรหมอก',
    fromIslandId: 'sunscar-desert',
    toIslandId: 'mist-jungle',
    fromDockId: 'sunscar-desert-harbor',
    toDockId: 'mist-jungle-harbor',
    distance: 170,
    recommendedCommodityIds: ['desert-salt', 'cactus-water'],
    notes: 'น้ำและเกลือขายดีในป่าชื้น',
  },
] as const;
