import type { TradeVendorDefinition } from '../types';

/** NPC ผู้ค้าต่อเกาะ — ผูกกับตลาดและพิกัดโลก */
export const TRADE_VENDORS: readonly TradeVendorDefinition[] = [
  {
    id: 'vendor-starter-pao',
    islandId: 'starter-island',
    name: 'Pao the Trader',
    nameTh: 'เถ้าแก่เปา',
    kind: 'general',
    marketId: 'starter-market',
    x: 6,
    z: 4,
    dialogueOpen: 'ของจากทะเลและป่าไม้ ซื้อขายได้ที่นี่!',
  },
  {
    id: 'vendor-starter-harbor',
    islandId: 'starter-island',
    name: 'Harbor Broker Kram',
    nameTh: 'นายท่าคราม',
    kind: 'harbor',
    marketId: 'starter-market',
    x: 2,
    z: -35,
    dialogueOpen: 'จะลงสินค้าหรือรับของขึ้นเรือ?',
  },
  {
    id: 'vendor-mist-expedition',
    islandId: 'mist-jungle',
    name: 'Expedition Quartermaster',
    nameTh: 'เจ้าหน้าที่ค่ายสำรวจ',
    kind: 'general',
    marketId: 'mist-jungle-market',
    x: 156,
    z: -38,
    dialogueOpen: 'สมุนไพรและของโบราณจากป่า — แลกกับเสบียงจากทะเล',
  },
  {
    id: 'vendor-mist-harbor',
    islandId: 'mist-jungle',
    name: 'Jungle Dock Trader',
    nameTh: 'พ่อค้าท่าเรือป่า',
    kind: 'harbor',
    marketId: 'mist-jungle-market',
    x: 140,
    z: -42,
    dialogueOpen: 'ขึ้นเรือก่อนออกเดินทาง อย่าลืมเช็ค cargo',
  },
  {
    id: 'vendor-sunscar-bazaar',
    islandId: 'sunscar-desert',
    name: 'Caravan Master Sahir',
    nameTh: 'หัวหน้าคาราวานซาฮีร์',
    kind: 'caravan',
    marketId: 'sunscar-desert-market',
    x: 168,
    z: 98,
    dialogueOpen: 'ผ้าไหมและอัญมณีจากทะเลทราย — ราคาดีวันนี้',
  },
  {
    id: 'vendor-sunscar-harbor',
    islandId: 'sunscar-desert',
    name: 'Desert Harbor Merchant',
    nameTh: 'พ่อค้าท่าเรือทราย',
    kind: 'harbor',
    marketId: 'sunscar-desert-market',
    x: 177,
    z: 78,
    dialogueOpen: 'ลงสินค้าจากเรือหรือเติมเสบียงก่อนออกทะเล?',
  },
] as const;
