import type { TradeVendorDefinition } from '../types';
import { layoutPoint } from '../../island/IslandRegistry';

/** NPC ผู้ค้า — ผูกกับตลาด Living Trade */
const LEGACY_TRADE_VENDORS: readonly TradeVendorDefinition[] = [
  {
    id: 'vendor-starter-pao',
    islandId: 'starter-island',
    name: 'Pao the Trader',
    nameTh: 'เถ้าแก่เปา',
    kind: 'general',
    marketId: 'starter-market',
    x: 6,
    z: 4,
    dialogueOpen: 'เกาะใบไม้ — อาหารและไม้ราคาตามตลาดจริง',
  },
  {
    id: 'vendor-starter-shipyard',
    islandId: 'starter-island',
    name: 'Shipwright Mek',
    nameTh: 'ช่างเรือเมฆ',
    kind: 'harbor',
    marketId: 'starter-shipyard-market',
    x: 4,
    z: -33,
    dialogueOpen: 'อู่เรือ — ซื้อขายชิ้นส่วนเรือ ราคาเปลี่ยนตามวัตถุดิบ',
  },
  {
    id: 'vendor-mist-expedition',
    islandId: 'mist-jungle',
    name: 'Expedition Quartermaster',
    nameTh: 'เจ้าหน้าที่ค่ายเหมือง',
    kind: 'general',
    marketId: 'mist-jungle-market',
    x: 156,
    z: -38,
    dialogueOpen: 'เกาะเหมือง — เหล็กส่งออก ต้องการอาหารและไม้',
  },
  {
    id: 'vendor-mist-harbor',
    islandId: 'mist-jungle',
    name: 'Jungle Dock Trader',
    nameTh: 'พ่อค้าท่าเรือป่า',
    kind: 'harbor',
    marketId: 'mist-jungle-market',
    x: 140,
    z: -42,
    dialogueOpen: 'ตลาดท่าเรือ — ราคาสดจากเศรษฐกิจภูมิภาค',
  },
  {
    id: 'vendor-sunscar-bazaar',
    islandId: 'sunscar-desert',
    name: 'Caravan Master Sahir',
    nameTh: 'หัวหน้าคาราวานซาฮีร์',
    kind: 'caravan',
    marketId: 'sunscar-desert-market',
    x: 168,
    z: 98,
    dialogueOpen: 'เกาะทอผ้า — ผ้าไหมและสินค้านำเข้า',
  },
  {
    id: 'vendor-sunscar-harbor',
    islandId: 'sunscar-desert',
    name: 'Desert Harbor Merchant',
    nameTh: 'พ่อค้าท่าเรือทราย',
    kind: 'harbor',
    marketId: 'sunscar-desert-market',
    x: 177,
    z: 78,
    dialogueOpen: 'ลงสินค้าจากเรือ — ราคาเปลี่ยนทุก 5 วินาที',
  },
  {
    id: 'vendor-frost-market',
    islandId: 'azure-frost',
    name: 'Frost Harbor Broker',
    nameTh: 'นายหน้าท่าเหมันต์',
    kind: 'general',
    marketId: 'azure-frost-market',
    x: 61,
    z: 202,
    dialogueOpen: 'เกาะเหมันต์คราม — ผลึกเย็นส่งออก สินค้านำเข้ามีน้อยจึงราคาสูง',
  },
  {
    id: 'vendor-frost-harbor',
    islandId: 'azure-frost',
    name: 'Tarin Frost Shipping',
    nameTh: 'พ่อค้าขนส่งเหมันต์',
    kind: 'harbor',
    marketId: 'azure-frost-market',
    x: 67,
    z: 193,
    dialogueOpen: 'รับของจากเรือทุกเส้นทาง — เช็กสต็อกนำเข้าและราคาก่อนซื้อ',
  },
  {
    id: 'vendor-tempest-market',
    islandId: 'tempest-sky',
    name: 'Tempest Sky Broker',
    nameTh: 'นายหน้าตลาดนภา',
    kind: 'general',
    marketId: 'tempest-sky-market',
    x: -92,
    z: 214,
    dialogueOpen: 'เกาะนภาวายุ — แกนพายุส่งออก ส่วนอาหารและวัสดุถูกส่งขึ้นมาทีละน้อย',
  },
  {
    id: 'vendor-tempest-harbor',
    islandId: 'tempest-sky',
    name: 'Tempest Dock Broker',
    nameTh: 'พ่อค้าท่าเรือนภา',
    kind: 'harbor',
    marketId: 'tempest-sky-market',
    x: -99,
    z: 207,
    dialogueOpen: 'ท่าเรือนภา — สินค้านำเข้าราคาแปรผันตามจำนวนเรือสินค้าที่มาถึง',
  },
  {
    id: 'vendor-ember-market',
    islandId: 'ember-volcano',
    name: 'Ember Forge Broker',
    nameTh: 'นายหน้าตลาดอัคคี',
    kind: 'general',
    marketId: 'ember-volcano-market',
    x: -220,
    z: 105,
    dialogueOpen: 'เกาะภูผาอัคคี — แร่อัคคีส่งออก อาหารและของเย็นต้องนำเข้าราคาแพง',
  },
  {
    id: 'vendor-ember-harbor',
    islandId: 'ember-volcano',
    name: 'Ember Harbor Broker',
    nameTh: 'พ่อค้าท่าภูผา',
    kind: 'harbor',
    marketId: 'ember-volcano-market',
    x: -216,
    z: 104,
    dialogueOpen: 'ท่าเรือภูผา — ดูสินค้าบนเรือและเติมเสบียงก่อนเข้าปล่องไฟ',
  },
] as const;

export const TRADE_VENDORS: readonly TradeVendorDefinition[] = LEGACY_TRADE_VENDORS.map((vendor) => ({
  ...vendor,
  ...layoutPoint(vendor.islandId, vendor.x, vendor.z),
}));
