import type { TradeVendorDefinition } from '../types';

/** NPC ผู้ค้า — ผูกกับตลาด Living Trade */
export const TRADE_VENDORS: readonly TradeVendorDefinition[] = [
  {
    id: 'vendor-starter-pao',
    islandId: 'starter-island',
    name: 'Pao the Trader',
    nameTh: 'เถ้าแก่เปา',
    kind: 'general',
    marketId: 'starter-market',
    x: 6,
    z: 4,
    dialogueOpen: 'เกาะใบไม้ — อาหารและไม้ราคาตามตลาดจริง',
  },
  {
    id: 'vendor-starter-shipyard',
    islandId: 'starter-island',
    name: 'Shipwright Mek',
    nameTh: 'ช่างเรือเมฆ',
    kind: 'harbor',
    marketId: 'starter-shipyard-market',
    x: 4,
    z: -33,
    dialogueOpen: 'อู่เรือ — ซื้อขายชิ้นส่วนเรือ ราคาเปลี่ยนตามวัตถุดิบ',
  },
  {
    id: 'vendor-mist-expedition',
    islandId: 'mist-jungle',
    name: 'Expedition Quartermaster',
    nameTh: 'เจ้าหน้าที่ค่ายเหมือง',
    kind: 'general',
    marketId: 'mist-jungle-market',
    x: 156,
    z: -38,
    dialogueOpen: 'เกาะเหมือง — เหล็กส่งออก ต้องการอาหารและไม้',
  },
  {
    id: 'vendor-mist-harbor',
    islandId: 'mist-jungle',
    name: 'Jungle Dock Trader',
    nameTh: 'พ่อค้าท่าเรือป่า',
    kind: 'harbor',
    marketId: 'mist-jungle-market',
    x: 140,
    z: -42,
    dialogueOpen: 'ตลาดท่าเรือ — ราคาสดจากเศรษฐกิจภูมิภาค',
  },
  {
    id: 'vendor-sunscar-bazaar',
    islandId: 'sunscar-desert',
    name: 'Caravan Master Sahir',
    nameTh: 'หัวหน้าคาราวานซาฮีร์',
    kind: 'caravan',
    marketId: 'sunscar-desert-market',
    x: 168,
    z: 98,
    dialogueOpen: 'เกาะทอผ้า — ผ้าไหมและสินค้านำเข้า',
  },
  {
    id: 'vendor-sunscar-harbor',
    islandId: 'sunscar-desert',
    name: 'Desert Harbor Merchant',
    nameTh: 'พ่อค้าท่าเรือทราย',
    kind: 'harbor',
    marketId: 'sunscar-desert-market',
    x: 177,
    z: 78,
    dialogueOpen: 'ลงสินค้าจากเรือ — ราคาเปลี่ยนทุก 5 วินาที',
  },
] as const;
