import type { SwordSkillDefinition } from '../types';

export const SWORD_SKILLS: readonly SwordSkillDefinition[] = [
  {
    "id": "bisento-v1-z",
    "swordId": "bisento",
    "key": "Z",
    "name": "Wind Breaker",
    "mastery": 50,
    "cooldown": 9,
    "energy": 20,
    "breaksInstinct": false,
    "description": "The user raises their Bisento, then slams it down onto the ground, releasing 3 slashes that do good damage. This move is similar to Triple Dark Blade's [X] move and Mammoth's [Z] move untransformed.",
    "version": "v1"
  },
  {
    "id": "bisento-v1-x",
    "swordId": "bisento",
    "key": "X",
    "name": "Quake Sphere",
    "mastery": 150,
    "cooldown": 13.5,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user creates a white sphere on the tip of their Bisento and then launches it. It pulls in nearby enemies and does minimal damage when hit, then expands and does good damage.",
    "version": "v1"
  },
  {
    "id": "bisento-v2-z",
    "swordId": "bisento",
    "key": "Z",
    "name": "Wind Breaker",
    "mastery": 50,
    "cooldown": 9,
    "energy": 20,
    "breaksInstinct": false,
    "description": "The user raises their Bisento, then slams it down onto the ground, releasing 3 slashes that do good damage. This move is similar to Triple Dark Blade's [X] move and Mammoth's [Z] move untransformed.",
    "version": "v2"
  },
  {
    "id": "bisento-v2-x",
    "swordId": "bisento",
    "key": "X",
    "name": "Quake Sphere",
    "mastery": 150,
    "cooldown": 13.5,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user creates a white sphere on the tip of their Bisento and then launches it. It pulls in nearby enemies and does minimal damage when hit, then expands and does good damage.",
    "version": "v2"
  },
  {
    "id": "buddy-sword-z",
    "swordId": "buddy-sword",
    "key": "Z",
    "name": "Heat Slash",
    "mastery": null,
    "cooldown": 9,
    "energy": 20,
    "breaksInstinct": true,
    "description": "",
    "version": "base"
  },
  {
    "id": "buddy-sword-x",
    "swordId": "buddy-sword",
    "key": "X",
    "name": "Lightning Wave",
    "mastery": null,
    "cooldown": 13.5,
    "energy": 40,
    "breaksInstinct": true,
    "description": "",
    "version": "base"
  },
  {
    "id": "canvander-z",
    "swordId": "canvander",
    "key": "Z",
    "name": "Piercing Dash",
    "mastery": 150,
    "cooldown": 9,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user dashes in the direction of their cursor, rapidly slashing enemies in their path, dealing damage and scattering purple-white flower petals.",
    "version": "base"
  },
  {
    "id": "canvander-x",
    "swordId": "canvander",
    "key": "X",
    "name": "Scattering Gust",
    "mastery": 300,
    "cooldown": 13.5,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user dashes forward, scattering purple-white flowers and launching five purple air slashes in the direction of their cursor. If the slashes hit an enemy, their and the user's screen will cover in a purple tint for a second.",
    "version": "base"
  },
  {
    "id": "cursed-dual-katana-z",
    "swordId": "cursed-dual-katana",
    "key": "Z",
    "name": "Revolving Ravager",
    "mastery": 175,
    "cooldown": 9,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user spins around, zooming their view out and forming a red and black tornado that stuns and damages targets that are near it. Afterwards, the user will unleash the tornado, which pulls enemies away and captures and drags any enemies in its path, and then explodes, which will fling enemies towards the user. While this move is held, the tornado will stay in place for some time, dealing extra damage.",
    "version": "base"
  },
  {
    "id": "cursed-dual-katana-x",
    "swordId": "cursed-dual-katana",
    "key": "X",
    "name": "Slayer of Goliath",
    "mastery": 375,
    "cooldown": 14,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The user executes a backflip before crossing their swords in an X pattern, dashing towards the enemy(s) at high speed, and slicing them, dealing high damage. This move can be held to go further and deal more damage. Additionally, when hit, a second explosion will occur, dealing slightly less damage and knocking the target back. Finally, the target will see a large quickly spinning X obstructing their screen when hit. This move can bypass the protection granted by Dragon and only a % of Buddha transformations.",
    "version": "base"
  },
  {
    "id": "cutlass-z",
    "swordId": "cutlass",
    "key": "Z",
    "name": "Quiet Rush",
    "mastery": 1,
    "cooldown": 7,
    "energy": 15,
    "breaksInstinct": false,
    "description": "The user dashes forward, swiftly attacking enemies in their path in a teleportation-like fashion.",
    "version": "base"
  },
  {
    "id": "cutlass-x",
    "swordId": "cutlass",
    "key": "X",
    "name": "Air Slash",
    "mastery": 20,
    "cooldown": 10,
    "energy": 25,
    "breaksInstinct": false,
    "description": "The user slashes through the air, unleashing a short-range air slash that strikes all enemies in its path, forcefully knocking them back.",
    "version": "base"
  },
  {
    "id": "dark-blade-v1-z",
    "swordId": "dark-blade",
    "key": "Z",
    "name": "One Thousand Slices",
    "mastery": 1,
    "cooldown": 8.5,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user executes a near instantaneous barrage of several black and white slashes, dealing high damage, hitting enemies, and stunning them for a short amount of time.",
    "version": "v1"
  },
  {
    "id": "dark-blade-v1-x",
    "swordId": "dark-blade",
    "key": "X",
    "name": "Dark Air Slash",
    "mastery": 50,
    "cooldown": 13,
    "energy": 40,
    "breaksInstinct": true,
    "description": "The user launches a thin, tall, vertical slash of black energy toward their cursor which deals high damage and has a little knockback. If held, the same move occurs, but the slash travels much faster and goes farther, this effect also only applies after evolving via The Son Quest.",
    "version": "v1"
  },
  {
    "id": "dark-blade-v2-z",
    "swordId": "dark-blade",
    "key": "Z",
    "name": "One Thousand Slices",
    "mastery": 1,
    "cooldown": 8.5,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user executes a near instantaneous barrage of several black and white slashes, dealing high damage, hitting enemies, and stunning them for a short amount of time.",
    "version": "v2"
  },
  {
    "id": "dark-blade-v2-x",
    "swordId": "dark-blade",
    "key": "X",
    "name": "Dark Air Slash",
    "mastery": 50,
    "cooldown": 13,
    "energy": 40,
    "breaksInstinct": true,
    "description": "The user launches a thin, tall, vertical slash of black energy toward their cursor which deals high damage and has a little knockback. If held, the same move occurs, but the slash travels much faster and goes farther, this effect also only applies after evolving via The Son Quest.",
    "version": "v2"
  },
  {
    "id": "dark-blade-v3-z",
    "swordId": "dark-blade",
    "key": "Z",
    "name": "One Thousand Slices",
    "mastery": 1,
    "cooldown": 8.5,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user executes a near instantaneous barrage of several black and white slashes, dealing high damage, hitting enemies, and stunning them for a short amount of time.",
    "version": "v3"
  },
  {
    "id": "dark-blade-v3-x",
    "swordId": "dark-blade",
    "key": "X",
    "name": "Dark Air Slash",
    "mastery": 50,
    "cooldown": 13,
    "energy": 40,
    "breaksInstinct": true,
    "description": "The user launches a thin, tall, vertical slash of black energy toward their cursor which deals high damage and has a little knockback. If held, the same move occurs, but the slash travels much faster and goes farther, this effect also only applies after evolving via The Son Quest.",
    "version": "v3"
  },
  {
    "id": "dark-dagger-z",
    "swordId": "dark-dagger",
    "key": "Z",
    "name": "Proficient Impale",
    "mastery": 150,
    "cooldown": 9.5,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user initiates a stance before rushing forward, creating an impact of green electrical-like shock when an entity is hit. This attack breaks Instinct.",
    "version": "base"
  },
  {
    "id": "dark-dagger-x",
    "swordId": "dark-dagger",
    "key": "X",
    "name": "Shaming Slash",
    "mastery": 300,
    "cooldown": 13.5,
    "energy": 40,
    "breaksInstinct": true,
    "description": "The user shoots a short, green, electrical, glowing dagger. If it comes in contact with an entity, the user will teleport behind and slash them.",
    "version": "base"
  },
  {
    "id": "dragon-trident-z",
    "swordId": "dragon-trident",
    "key": "Z",
    "name": "Sea Dragon Fury",
    "mastery": 150,
    "cooldown": 9,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user fires a large water dragon's head at the direction of their cursor, damaging and pushing away enemies in its path similar to Magma awakened  move. This move has high knockback.",
    "version": "base"
  },
  {
    "id": "dragon-trident-x",
    "swordId": "dragon-trident",
    "key": "X",
    "name": "Water Dragon Shower",
    "mastery": 350,
    "cooldown": 13.5,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The user summons a whirlpool of water dragons with a large AoE. This has a really short knockback, producing an effect almost like a stun.",
    "version": "base"
  },
  {
    "id": "dragonheart-z",
    "swordId": "dragonheart",
    "key": "Z",
    "name": "Draconic Blitz",
    "mastery": 150,
    "cooldown": 9,
    "energy": 30,
    "breaksInstinct": false,
    "description": "The user summons a dragon that swirls in an almost zig-zag path, which is carried by the user as they lunge forward, carrying the enemy as well whilst the dragon burns away and crackles, similar to an ignited fuse.",
    "version": "base"
  },
  {
    "id": "dragonheart-x",
    "swordId": "dragonheart",
    "key": "X",
    "name": "Infernal Catastrophe",
    "mastery": 350,
    "cooldown": 13.5,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The user holds Dragonheart upwards, creating a large flaming ball similar to Flame's [V] move, then launches it at the aimed position, resulting in an extreme shockwave and fiery explosion, leaving a trail of flames and dealing massive damage. When the move is held, the user's screen slightly shifts into red with embers scattered awaft, the ball of fire grows larger, and a circle of flames and embers surround the user, dealing damage to any enemies within it. The explosion also tends to \"latch onto\" walls if it makes contact with one.",
    "version": "base"
  },
  {
    "id": "dual-katana-z",
    "swordId": "dual-katana",
    "key": "Z",
    "name": "Whirlwind",
    "mastery": 1,
    "cooldown": 7,
    "energy": 15,
    "breaksInstinct": false,
    "description": "Sends out a medium-range, spherical slicing attack formed by arcs that carries and knocks back its targets.",
    "version": "base"
  },
  {
    "id": "dual-katana-x",
    "swordId": "dual-katana",
    "key": "X",
    "name": "Tornado",
    "mastery": 30,
    "cooldown": 13,
    "energy": 25,
    "breaksInstinct": true,
    "description": "Unleashes a violently rotating whirlwind attack that damages all enemies within its radius and flings them away.",
    "version": "base"
  },
  {
    "id": "dual-headed-blade-z",
    "swordId": "dual-headed-blade",
    "key": "Z",
    "name": "Assassinate",
    "mastery": 20,
    "cooldown": 7.5,
    "energy": 15,
    "breaksInstinct": false,
    "description": "The user dashes forward in a slow spinning motion, slashing enemies in their path and leaving a glittering trail behind them.",
    "version": "base"
  },
  {
    "id": "dual-headed-blade-x",
    "swordId": "dual-headed-blade",
    "key": "X",
    "name": "Raging Wind",
    "mastery": 100,
    "cooldown": 10,
    "energy": 25,
    "breaksInstinct": false,
    "description": "The user propels three small tornadoes towards the direction of their cursor, damaging enemies upon impact.",
    "version": "base"
  },
  {
    "id": "flail-z",
    "swordId": "flail",
    "key": "Z",
    "name": "Smoke Tiger",
    "mastery": 150,
    "cooldown": 9,
    "energy": null,
    "breaksInstinct": false,
    "description": "The user launches a Tiger-like blast of smoke in the direction of their cursor that travels for a long distance, briefly stunning, blinding, and damaging enemies hit.",
    "version": "base"
  },
  {
    "id": "flail-x",
    "swordId": "flail",
    "key": "X",
    "name": "Smoke Apparition",
    "mastery": 300,
    "cooldown": 12,
    "energy": null,
    "breaksInstinct": true,
    "description": "The user teleports to their cursor's location and releases billowing smoke, damaging and blinding nearby enemies for approximately two seconds. Smoke is left at both the original and destination points, dealing damage in both areas.",
    "version": "base"
  },
  {
    "id": "fox-lamp-z",
    "swordId": "fox-lamp",
    "key": "Z",
    "name": "Scorching Azure",
    "mastery": 150,
    "cooldown": 10,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user summons a rotating ring of blue letters that envelop the player. Once released, the azure embers swiftly move towards the target aimed at the cursor's location. Upon contact with an enemy, the azure embers inflict multiple slashing attacks before propelling the enemy into the air, resulting in a powerful explosion. If held, the letters transform into blue spheres that rotate around the player, though this is just a visual change and does not affect damage.",
    "version": "base"
  },
  {
    "id": "fox-lamp-x",
    "swordId": "fox-lamp",
    "key": "X",
    "name": "Infernal Firestorm",
    "mastery": 350,
    "cooldown": 13,
    "energy": 60,
    "breaksInstinct": true,
    "description": "This ability consists of two variations:",
    "version": "base"
  },
  {
    "id": "gravity-blade-z",
    "swordId": "gravity-blade",
    "key": "Z",
    "name": "Dimensional Grasp",
    "mastery": 125,
    "cooldown": 7.5,
    "energy": 15,
    "breaksInstinct": true,
    "description": "The user attracts all nearby enemies in the direction of the cursor, mustering a lavender aura before releasing it in an explosion.",
    "version": "base"
  },
  {
    "id": "gravity-blade-x",
    "swordId": "gravity-blade",
    "key": "X",
    "name": "Lunar Blitz",
    "mastery": 250,
    "cooldown": 10.5,
    "energy": 25,
    "breaksInstinct": true,
    "description": "The user reverses gravity and flings the target in the air, slashing them and dealing constant damage, before finally slamming them back into the ground.",
    "version": "base"
  },
  {
    "id": "hallow-scythe-z",
    "swordId": "hallow-scythe",
    "key": "Z",
    "name": "Death Cyclone",
    "mastery": 150,
    "cooldown": 9,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user initiates a stance before releasing an orange-black tornado with a decent hitbox, being able to destroy trees. This move causes knockback to entities hit by the tornado, dealing multiple ticks of damage in one attack.",
    "version": "base"
  },
  {
    "id": "hallow-scythe-x",
    "swordId": "hallow-scythe",
    "key": "X",
    "name": "Soul Execution",
    "mastery": 350,
    "cooldown": 13,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The user dashes forward, grabbing the nearest enemies, before ending the move with a strike, dealing knockback. This move is not limited to single targets. Move activates a brief period of flight, which is controllable. It does x1.2 more damage if the enemy's health is below 50%. This move breaks Instinct. The dash part of this move is  similar to Godhuman's  and Dragon's .",
    "version": "base"
  },
  {
    "id": "iron-mace-z",
    "swordId": "iron-mace",
    "key": "Z",
    "name": "Mace Smash",
    "mastery": null,
    "cooldown": 7,
    "energy": null,
    "breaksInstinct": true,
    "description": "",
    "version": "base"
  },
  {
    "id": "iron-mace-x",
    "swordId": "iron-mace",
    "key": "X",
    "name": "Killer Combo",
    "mastery": null,
    "cooldown": 11,
    "energy": null,
    "breaksInstinct": true,
    "description": "",
    "version": "base"
  },
  {
    "id": "katana-z",
    "swordId": "katana",
    "key": "Z",
    "name": "Quiet Rush",
    "mastery": 1,
    "cooldown": 7,
    "energy": 15,
    "breaksInstinct": false,
    "description": "The user dashes forward, swiftly attacking enemies in their path in a teleportation-like fashion.",
    "version": "base"
  },
  {
    "id": "katana-x",
    "swordId": "katana",
    "key": "X",
    "name": "Air Slash",
    "mastery": 20,
    "cooldown": 10,
    "energy": 25,
    "breaksInstinct": false,
    "description": "The user slashes through the air, unleashing a short-range air slash that strikes all enemies in its path, forcefully knocking them back.",
    "version": "base"
  },
  {
    "id": "koko-z",
    "swordId": "koko",
    "key": "Z",
    "name": "Electric Stab",
    "mastery": 150,
    "cooldown": 9,
    "energy": null,
    "breaksInstinct": false,
    "description": "The user charges forward with the power of electricity, damaging and shocking any opponents in the way, and launching them upwards.",
    "version": "base"
  },
  {
    "id": "koko-x",
    "swordId": "koko",
    "key": "X",
    "name": "Injection Shot",
    "mastery": 325,
    "cooldown": 13.5,
    "energy": null,
    "breaksInstinct": true,
    "description": "A rotating crosshair appears in front of the player. When released, a swift lightning projectile shoots out of the sword (does not have projectile mechanics), which damages and shocks any opponents hit by it, while also knocking them back slightly.",
    "version": "base"
  },
  {
    "id": "longsword-z",
    "swordId": "longsword",
    "key": "Z",
    "name": "Annihilate",
    "mastery": 100,
    "cooldown": 8,
    "energy": null,
    "breaksInstinct": false,
    "description": "The user dashes towards their cursor, then sends out a green slash that deals damage and creates temporary grass as it flies near a surface. If an enemy is hit by the dash, they become briefly stunned, take some extra damage and deal decent knockback.",
    "version": "base"
  },
  {
    "id": "longsword-x",
    "swordId": "longsword",
    "key": "X",
    "name": "Glorious Smash",
    "mastery": 200,
    "cooldown": 13,
    "energy": null,
    "breaksInstinct": true,
    "description": "The user jumps over the enemy, dealing damage and creating a grassy area launching the target upwards. If there is a player on top of them at the start of the leap, the user will drag the player that is in contact with them alongside the leap.",
    "version": "base"
  },
  {
    "id": "midnight-blade-z",
    "swordId": "midnight-blade",
    "key": "Z",
    "name": "Portal Opening",
    "mastery": 150,
    "cooldown": 7,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user shoots a virtual image of themselves in the direction of the mouse, which the user will then slash (which the virtual version of themselves copies), and on hit will trigger a small AoE domain of quantum energy, pulling enemies in range in and barraging them for the duration of the ability. Interestingly, this move stuns Blade users through the entire animation, although does not deal damage.",
    "version": "base"
  },
  {
    "id": "midnight-blade-x",
    "swordId": "midnight-blade",
    "key": "X",
    "name": "Crescent Dash",
    "mastery": 325,
    "cooldown": 10,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The user dashes forward, leaving behind a blue trail, which on hitting an enemy will pull in nearby enemies before making the player spin around then creating an AoE explosion and throwing the enemies forwards.",
    "version": "base"
  },
  {
    "id": "oroshi-z",
    "swordId": "oroshi",
    "key": "Z",
    "name": "Continuous Slashing",
    "mastery": 150,
    "cooldown": 8,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user rapidly slashes with the sword, creating a flurry of white sword slashes in front of them that continuously damages enemies within the area. The duration of this attack can be extended by holding the associated key, with a maximum duration of 5 seconds. After the move concludes, the sword slashes expand, knocking back enemies. This ability is similar to Spin's [Z] and Superhuman’s [Z] move.",
    "version": "base"
  },
  {
    "id": "oroshi-x",
    "swordId": "oroshi",
    "key": "X",
    "name": "Dragon Gust",
    "mastery": 300,
    "cooldown": null,
    "energy": null,
    "breaksInstinct": false,
    "description": "The user dashes forward, grabs the opponent and shoots a ball of wind that deals slight knockback upon impact.",
    "version": "base"
  },
  {
    "id": "pipe-z",
    "swordId": "pipe",
    "key": "Z",
    "name": "Pipe Ignition",
    "mastery": 1,
    "cooldown": 7.5,
    "energy": 15,
    "breaksInstinct": false,
    "description": "This attack has two variants:",
    "version": "base"
  },
  {
    "id": "pipe-x",
    "swordId": "pipe",
    "key": "X",
    "name": "Dragon Blast",
    "mastery": 50,
    "cooldown": 10.5,
    "energy": 25,
    "breaksInstinct": false,
    "description": "The user shoots a small dragon-like blast of flame towards where their cursor is. Any enemy caught in the projectile will be dragged with it. When it reaches its cursor's point or goes far enough, it explodes and releases a fiery burst similar to awakened Flame X, causing burn damage to those that are in it.",
    "version": "base"
  },
  {
    "id": "pole-1st-form-z",
    "swordId": "pole-1st-form",
    "key": "Z",
    "name": "Explosive Cloud",
    "mastery": 80,
    "cooldown": 7.5,
    "energy": 15,
    "breaksInstinct": true,
    "description": "The user waves the pole in the air, shooting out an invisible cloud from the top in the direction of their cursor. Once it reaches its maximum distance or hits a surface, it will create an electric explosion that deals decent damage and stuns the enemy for a bit.",
    "version": "base"
  },
  {
    "id": "pole-1st-form-x",
    "swordId": "pole-1st-form",
    "key": "X",
    "name": "Lightning Rain",
    "mastery": 180,
    "cooldown": 10.5,
    "energy": 25,
    "breaksInstinct": true,
    "description": "The user waves the pole in the air, creating a small cloud at their cursor. The cloud will then strike down three bolts of lightning which hits enemies below it, which deals decent damage.",
    "version": "base"
  },
  {
    "id": "pole-2nd-form-z",
    "swordId": "pole-2nd-form",
    "key": "Z",
    "name": "Hand of God",
    "mastery": 150,
    "cooldown": 9,
    "energy": 30,
    "breaksInstinct": false,
    "description": "The user fires three lightning beams from the pole towards the direction of their cursor, which deals damage to nearby enemies and stuns them. Blue lightning strike marks are left where the beams hit.",
    "version": "base"
  },
  {
    "id": "pole-2nd-form-x",
    "swordId": "pole-2nd-form",
    "key": "X",
    "name": "Electric Prison",
    "mastery": 350,
    "cooldown": 13.5,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The user forms a small electric sphere at the location of their cursor, stunning enemies and pulling them in towards the centre of the sphere.",
    "version": "base"
  },
  {
    "id": "rengoku-z",
    "swordId": "rengoku",
    "key": "Z",
    "name": "Demon Slayer",
    "mastery": 150,
    "cooldown": 9,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user dashes forward, leaving a trail of orange and red flames. If the user hits an enemy, the user slashes the enemy rapidly and finally releases three fire-like slashes, dealing tick damage with a burn effect. The burn lasts for around 2 seconds.",
    "version": "base"
  },
  {
    "id": "rengoku-x",
    "swordId": "rengoku",
    "key": "X",
    "name": "Burning Slash",
    "mastery": 350,
    "cooldown": 13.5,
    "energy": 30,
    "breaksInstinct": true,
    "description": "This move offers two distinct variations:",
    "version": "base"
  },
  {
    "id": "saber-v1-z",
    "swordId": "saber",
    "key": "Z",
    "name": "Deadly Rush",
    "mastery": 50,
    "cooldown": 7.5,
    "energy": 15,
    "breaksInstinct": false,
    "description": "The user charges up, dashes forward, and this time sends two air slashes flying. This move is, in theory, V1's [Z] combined with V1's [X]. There's an area where the two moves combine, and once the user manages to land it on the enemy, will deal extremely high damage due to it being the equivalent of two sword moves at once.",
    "version": "v1"
  },
  {
    "id": "saber-v1-x",
    "swordId": "saber",
    "key": "X",
    "name": "Triple Slash",
    "mastery": 125,
    "cooldown": 14,
    "energy": 30,
    "breaksInstinct": false,
    "description": "The user sends a red projectile made out of four beams in the direction of their cursor, doing more damage than its V1 counterpart and having a larger hitbox.",
    "version": "v1"
  },
  {
    "id": "saber-v2-z",
    "swordId": "saber",
    "key": "Z",
    "name": "Deadly Rush",
    "mastery": 50,
    "cooldown": 7.5,
    "energy": 15,
    "breaksInstinct": false,
    "description": "The user charges up, dashes forward, and this time sends two air slashes flying. This move is, in theory, V1's [Z] combined with V1's [X]. There's an area where the two moves combine, and once the user manages to land it on the enemy, will deal extremely high damage due to it being the equivalent of two sword moves at once.",
    "version": "v2"
  },
  {
    "id": "saber-v2-x",
    "swordId": "saber",
    "key": "X",
    "name": "Triple Slash",
    "mastery": 125,
    "cooldown": 14,
    "energy": 30,
    "breaksInstinct": false,
    "description": "The user sends a red projectile made out of four beams in the direction of their cursor, doing more damage than its V1 counterpart and having a larger hitbox.",
    "version": "v2"
  },
  {
    "id": "saishi-z",
    "swordId": "saishi",
    "key": "Z",
    "name": "Swords Dance",
    "mastery": 150,
    "cooldown": 8,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user dashes forward, leaving behind a golden trail. When in contact with an enemy, the user performs multiple vertical slashes before launching them upwards.",
    "version": "base"
  },
  {
    "id": "saishi-x",
    "swordId": "saishi",
    "key": "X",
    "name": "True Air Slash",
    "mastery": 300,
    "cooldown": 13,
    "energy": 30,
    "breaksInstinct": false,
    "description": "The user launches a large, golden air slash in the direction of their cursor, which damages and pushes back enemies hit by it.",
    "version": "base"
  },
  {
    "id": "shark-anchor-z",
    "swordId": "shark-anchor",
    "key": "Z",
    "name": "Typhoon Toss",
    "mastery": 150,
    "cooldown": 9,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user starts to rapidly rotate the anchor with a chain, similar to awakened Dough [C] then the user shoots a fast water shark in the direction of the mouse. When this projectile makes contact with something, a water tornado is formed and explodes, throwing it upwards. This attack gets bigger if the user charges this skill.",
    "version": "base"
  },
  {
    "id": "shark-anchor-x",
    "swordId": "shark-anchor",
    "key": "X",
    "name": "Armor Breaker",
    "mastery": 350,
    "cooldown": 13.5,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The user dashes forward, performing an uppercut with the sword. Enemies hit will be dragged along and slammed down, creating an anchor symbol on the ground if performed close to it. Creates a pink shatter and red slash effect and deals more damage if used against big targets. These include: Sea Beasts, ships, Terrorsharks, Factory Core, Leviathan, and Lava Golem's. This move also reduces armor from transformed players as Buddha users, Mammoth users, Dragon users, etc.",
    "version": "base"
  },
  {
    "id": "shark-saw-z",
    "swordId": "shark-saw",
    "key": "Z",
    "name": "Consecutive Slashes",
    "mastery": 10,
    "cooldown": 8,
    "energy": 15,
    "breaksInstinct": false,
    "description": "The user swings the sword two times diagonally before releasing a heavy slash vertically, knocking the enemy back. The slashes have a black and dark red aura.",
    "version": "base"
  },
  {
    "id": "shark-saw-x",
    "swordId": "shark-saw",
    "key": "X",
    "name": "Execution",
    "mastery": 60,
    "cooldown": 12,
    "energy": 25,
    "breaksInstinct": true,
    "description": "The user spins around in a circle while moving towards the cursor, slashing the sword around them. When hitting an enemy, they get pulled in and receive continuous damage. When the move finishes, the player does a small horizontal slash, dealing knockback and damage to the enemies caught in by the attack.",
    "version": "base"
  },
  {
    "id": "shizu-z",
    "swordId": "shizu",
    "key": "Z",
    "name": "True Quiet Rush",
    "mastery": 150,
    "cooldown": 9,
    "energy": 20,
    "breaksInstinct": false,
    "description": "The user dashes in the direction of their cursor, dealing damage to enemies in their path. Purple energy bursts from the user after their dash. This slightly stuns the enemies that were hit, similar to Katana's [Z] move.",
    "version": "base"
  },
  {
    "id": "shizu-x",
    "swordId": "shizu",
    "key": "X",
    "name": "Focus Shot",
    "mastery": 300,
    "cooldown": 13.5,
    "energy": 30,
    "breaksInstinct": false,
    "description": "The user swiftly fires an extremely fast purple projectile followed by a purple trail in the direction of their cursor. It slightly stuns and causes knockback when hit.",
    "version": "base"
  },
  {
    "id": "soul-cane-z",
    "swordId": "soul-cane",
    "key": "Z",
    "name": "Soul Beam",
    "mastery": 40,
    "cooldown": 7.5,
    "energy": 25,
    "breaksInstinct": true,
    "description": "The user shoots a thin white beam in the direction of their cursor, which explodes after travelling a short distance. The explosion damages and freezes enemies hit by it for around 1.5 seconds, similar to unawakened Ice's . Sounds like awakened Light's [C] Lightspeed Destroyer",
    "version": "base"
  },
  {
    "id": "soul-cane-x",
    "swordId": "soul-cane",
    "key": "X",
    "name": "Soul Slashes",
    "mastery": 120,
    "cooldown": 13.5,
    "energy": 30,
    "breaksInstinct": false,
    "description": "The user rapidly slashes with their sword, launching several air slashes that travel a short distance in the direction of their cursor, damaging enemies hit by them and stunning them for two seconds. This move is similar to Spider's [Z] Thermal Laceration.",
    "version": "base"
  },
  {
    "id": "spikey-trident-z",
    "swordId": "spikey-trident",
    "key": "Z",
    "name": "Dough Hurricane",
    "mastery": 150,
    "cooldown": 9,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user dashes forward. If the user collides with an enemy during the dash, they will start burrowing/drilling dough into the enemy's back while continuing the dash, dealing damage and stunning the enemy. The enemy will receive a fair amount of knockback afterwards.",
    "version": "base"
  },
  {
    "id": "spikey-trident-x",
    "swordId": "spikey-trident",
    "key": "X",
    "name": "Flying Trident Pull",
    "mastery": 300,
    "cooldown": 13.5,
    "energy": 40,
    "breaksInstinct": false,
    "description": "Attaching a stream of liquid dough attached to the trident, the user expels it in the direction of their cursor. Upon connection between the dough and any surface, the user will \"pull\" themselves towards that specific surface. If the dough connects with another player/NPC, then instead of the user, the player or NPC with whom the trident was connected with will be pulled towards the user. This move is very similar to Trident's [Z].",
    "version": "base"
  },
  {
    "id": "trident-z",
    "swordId": "trident",
    "key": "Z",
    "name": "Trident Throw",
    "mastery": 50,
    "cooldown": 6,
    "energy": null,
    "breaksInstinct": false,
    "description": "The user throws the trident in the direction of their cursor, which is connected to the user's right hand via a black rope. Upon hitting an enemy, the target is damaged and pulled towards the user. Upon hitting terrain, the user is pulled towards the trident. This move can be very deadly if used correctly. It acts similar to Spikey Trident's [X] Flying Trident Pull move but slower.",
    "version": "base"
  },
  {
    "id": "trident-x",
    "swordId": "trident",
    "key": "X",
    "name": "Water Pulse",
    "mastery": 125,
    "cooldown": 11,
    "energy": null,
    "breaksInstinct": true,
    "description": "The user spins the trident, creating a suction force that pulls nearby enemies towards them. Simultaneously, a blue circle appears in an area around the player and explodes in a burst of bubble shortly after, knocking enemies back.",
    "version": "base"
  },
  {
    "id": "triple-dark-blade-z",
    "swordId": "triple-dark-blade",
    "key": "Z",
    "name": "One Thousand Slices",
    "mastery": 1,
    "cooldown": null,
    "energy": null,
    "breaksInstinct": false,
    "description": "The user launches an instantaneous barrage of multiple green slashes, hitting enemies and stunning them for a very short period of time. This move is the same as Dark Blade's .",
    "version": "base"
  },
  {
    "id": "triple-dark-blade-x",
    "swordId": "triple-dark-blade",
    "key": "X",
    "name": "Dark Air Slash",
    "mastery": 50,
    "cooldown": null,
    "energy": null,
    "breaksInstinct": false,
    "description": "The user launches three thin, tall, vertical slashes of green energy toward their opponent, which deals high damage and has a little knockback.",
    "version": "base"
  },
  {
    "id": "triple-katana-z",
    "swordId": "triple-katana",
    "key": "Z",
    "name": "Air Slashes Barrage",
    "mastery": 20,
    "cooldown": 7.5,
    "energy": 15,
    "breaksInstinct": false,
    "description": "The user swings their swords in front of them, releasing blue air slashes in the direction of their cursor. These air slashes will damage enemies upon contact.",
    "version": "base"
  },
  {
    "id": "triple-katana-x",
    "swordId": "triple-katana",
    "key": "X",
    "name": "Violent Rush",
    "mastery": 60,
    "cooldown": 12,
    "energy": 25,
    "breaksInstinct": false,
    "description": "The user lifts their swords and charges forward, leaving behind a trail of blue-colored air slashes. These slashes will damage enemies upon contact.",
    "version": "base"
  },
  {
    "id": "true-triple-katana-z",
    "swordId": "true-triple-katana",
    "key": "Z",
    "name": "Wolf Fang Rush",
    "mastery": 150,
    "cooldown": 8,
    "energy": 30,
    "breaksInstinct": false,
    "description": "The user dashes forward, creating a great shockwave that stuns the enemy. If the user hits an enemy, the user will slice the enemy four times, stunning them each slice. This move is similar to Rengoku's [Z] and Kitsune and Empyrean's [F].",
    "version": "base"
  },
  {
    "id": "true-triple-katana-x",
    "swordId": "true-triple-katana",
    "key": "X",
    "name": "Dragon Hurricane",
    "mastery": 350,
    "cooldown": 13,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The user summons a fast-paced dragon that if an enemy touches, the enemy will get blown towards the sky, and a tornado will appear. This tornado can hit enemies which have touched it, whether or not they were harmed by the summoned dragon-projectile.",
    "version": "base"
  },
  {
    "id": "tushita-z",
    "swordId": "tushita",
    "key": "Z",
    "name": "Heavenly Lunges",
    "mastery": 150,
    "cooldown": 9,
    "energy": 15,
    "breaksInstinct": true,
    "description": "The user stabs repeatedly in front of them that stun the enemy it hits. Holding the button makes it last longer. It then ends with a strong large stab which has a longer range, more damage, and knocks enemies away.",
    "version": "base"
  },
  {
    "id": "tushita-x",
    "swordId": "tushita",
    "key": "X",
    "name": "Celestial Ravager",
    "mastery": 300,
    "cooldown": 14,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user dashes and creates multiple red slashes with incredible speed, dealing high damage, leaving a brief \"X\" mark on the affected surface. This move has two separate slashes, if the players cursor is facing a different direction after the first slash, they will slash in that direction instead of straight.",
    "version": "base"
  },
  {
    "id": "twin-hooks-z",
    "swordId": "twin-hooks",
    "key": "Z",
    "name": "Sky Cyclone",
    "mastery": 150,
    "cooldown": 9,
    "energy": null,
    "breaksInstinct": false,
    "description": "The user swings their hooks in front of them, briefly creating a cyclone of red wind at the point of their cursor, which deals damage to nearby enemies and drags them downwards. If enemies are on the ground, they will slightly rise to the air.",
    "version": "base"
  },
  {
    "id": "twin-hooks-x",
    "swordId": "twin-hooks",
    "key": "X",
    "name": "Prehistoric Punt",
    "mastery": 300,
    "cooldown": 14,
    "energy": null,
    "breaksInstinct": true,
    "description": "The user throws their hooks at the direction of their cursor, which are connected to them via ropes. After throwing the move towards the cursor it will also somewhat auto-aim moving to any non allied person or enemy. Upon hitting an enemy, the user pulls themselves towards the target as a large dark spectral mammoth head with red glowing eyes appears behind them and rushes forward, launching the target into the air after dealing damage. This move is similar to Mammoth's [X] True Prehistoric Punt.",
    "version": "base"
  },
  {
    "id": "wardens-sword-z",
    "swordId": "wardens-sword",
    "key": "Z",
    "name": "Multi-Target Slash",
    "mastery": 35,
    "cooldown": 9,
    "energy": 15,
    "breaksInstinct": true,
    "description": "The user smashes their blade into the ground, creating a blue shockwave that damages all enemies around them and knocks them back.",
    "version": "base"
  },
  {
    "id": "wardens-sword-x",
    "swordId": "wardens-sword",
    "key": "X",
    "name": "Tornado Slash",
    "mastery": 80,
    "cooldown": 15,
    "energy": 25,
    "breaksInstinct": false,
    "description": "The user launches a tornado in the direction of their cursor that launches any enemy it hits into the air.",
    "version": "base"
  },
  {
    "id": "yama-z",
    "swordId": "yama",
    "key": "Z",
    "name": "Hellish Slash",
    "mastery": 150,
    "cooldown": 9,
    "energy": 20,
    "breaksInstinct": false,
    "description": "The user performs a spinning slash, rapidly rotating while moving towards the target cursor. This attack carries significant knockback and inflicts decent damage. If the user successfully connects with both the spinning slash and the subsequent air slash, the combined strike will inflict slightly higher damage.",
    "version": "base"
  },
  {
    "id": "yama-x",
    "swordId": "yama",
    "key": "X",
    "name": "Infernal Hurricane",
    "mastery": 300,
    "cooldown": 14,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user enters a stance, charging an attack while black and red slashes appear for a split second. Upon releasing the button, the user swiftly dashes forward, executing a rapid tornado of slashes on the opponent, dealing decent damage while the tornado drags the enemy forward in a stun.",
    "version": "base"
  }
] as const;

export const SWORD_SKILL_BY_ID: Readonly<Record<string, SwordSkillDefinition>> = Object.fromEntries(SWORD_SKILLS.map((s) => [s.id, s]));
