/** Generated from client skillGameplay catalog; do not hand-edit. */
export interface SkillResourceCatalogEntry { id: string; slot: string; cooldownMs: number; mpCost: number; }
export const SKILL_RESOURCE_CATALOG: Readonly<Record<string, SkillResourceCatalogEntry>> = {
  'rocket-base-z': { id: 'rocket-base-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'rocket-base-x': { id: 'rocket-base-x', slot: 'X', cooldownMs: 10500, mpCost: 25 },
  'rocket-base-c': { id: 'rocket-base-c', slot: 'C', cooldownMs: 14250, mpCost: 35 },
  'rocket-base-f': { id: 'rocket-base-f', slot: 'F', cooldownMs: 7500, mpCost: 35 },
  'spin-base-z': { id: 'spin-base-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'spin-base-x': { id: 'spin-base-x', slot: 'X', cooldownMs: 11000, mpCost: 25 },
  'spin-base-c': { id: 'spin-base-c', slot: 'C', cooldownMs: 14250, mpCost: 35 },
  'spin-base-f': { id: 'spin-base-f', slot: 'F', cooldownMs: 7500, mpCost: 50 },
  'blade-base-m1': { id: 'blade-base-m1', slot: 'M1', cooldownMs: 300, mpCost: 4 },
  'blade-base-z': { id: 'blade-base-z', slot: 'Z', cooldownMs: 3750, mpCost: 15 },
  'blade-base-x': { id: 'blade-base-x', slot: 'X', cooldownMs: 9000, mpCost: 25 },
  'blade-base-c': { id: 'blade-base-c', slot: 'C', cooldownMs: 12000, mpCost: 35 },
  'blade-base-f': { id: 'blade-base-f', slot: 'F', cooldownMs: 4500, mpCost: 35 },
  'spring-base-z': { id: 'spring-base-z', slot: 'Z', cooldownMs: 6000, mpCost: 15 },
  'spring-base-x': { id: 'spring-base-x', slot: 'X', cooldownMs: 9000, mpCost: 25 },
  'spring-base-c': { id: 'spring-base-c', slot: 'C', cooldownMs: 13500, mpCost: 35 },
  'spring-base-v': { id: 'spring-base-v', slot: 'V', cooldownMs: 19500, mpCost: 65 },
  'spring-base-f': { id: 'spring-base-f', slot: 'F', cooldownMs: 6000, mpCost: 35 },
  'bomb-base-m1': { id: 'bomb-base-m1', slot: 'M1', cooldownMs: 3000, mpCost: 5 },
  'bomb-base-z': { id: 'bomb-base-z', slot: 'Z', cooldownMs: 4500, mpCost: 15 },
  'bomb-base-x': { id: 'bomb-base-x', slot: 'X', cooldownMs: 9000, mpCost: 25 },
  'bomb-base-c': { id: 'bomb-base-c', slot: 'C', cooldownMs: 11000, mpCost: 50 },
  'bomb-base-v': { id: 'bomb-base-v', slot: 'V', cooldownMs: 22500, mpCost: 100 },
  'bomb-base-f': { id: 'bomb-base-f', slot: 'F', cooldownMs: 6000, mpCost: 25 },
  'smoke-base-z': { id: 'smoke-base-z', slot: 'Z', cooldownMs: 5250, mpCost: 15 },
  'smoke-base-x': { id: 'smoke-base-x', slot: 'X', cooldownMs: 9000, mpCost: 25 },
  'smoke-base-c': { id: 'smoke-base-c', slot: 'C', cooldownMs: 13500, mpCost: 50 },
  'smoke-base-f': { id: 'smoke-base-f', slot: 'F', cooldownMs: 4500, mpCost: 50 },
  'spike-base-z': { id: 'spike-base-z', slot: 'Z', cooldownMs: 6000, mpCost: 20 },
  'spike-base-x': { id: 'spike-base-x', slot: 'X', cooldownMs: 10500, mpCost: 35 },
  'spike-base-c': { id: 'spike-base-c', slot: 'C', cooldownMs: 13500, mpCost: 50 },
  'spike-base-v': { id: 'spike-base-v', slot: 'V', cooldownMs: 12000, mpCost: 40 },
  'flame-moveset-v1-z': { id: 'flame-moveset-v1-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'flame-moveset-v1-x': { id: 'flame-moveset-v1-x', slot: 'X', cooldownMs: 10500, mpCost: 25 },
  'flame-moveset-v1-c': { id: 'flame-moveset-v1-c', slot: 'C', cooldownMs: 15000, mpCost: 35 },
  'flame-moveset-v1-v': { id: 'flame-moveset-v1-v', slot: 'V', cooldownMs: 27000, mpCost: 50 },
  'flame-moveset-v1-f': { id: 'flame-moveset-v1-f', slot: 'F', cooldownMs: 15000, mpCost: 100 },
  'flame-moveset-v2-z': { id: 'flame-moveset-v2-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'flame-moveset-v2-x': { id: 'flame-moveset-v2-x', slot: 'X', cooldownMs: 10500, mpCost: 25 },
  'flame-moveset-v2-c': { id: 'flame-moveset-v2-c', slot: 'C', cooldownMs: 15000, mpCost: 35 },
  'flame-moveset-v2-v': { id: 'flame-moveset-v2-v', slot: 'V', cooldownMs: 27000, mpCost: 50 },
  'flame-moveset-v2-f': { id: 'flame-moveset-v2-f', slot: 'F', cooldownMs: 12000, mpCost: 100 },
  'ice-moveset-v1-z': { id: 'ice-moveset-v1-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'ice-moveset-v1-x': { id: 'ice-moveset-v1-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'ice-moveset-v1-c': { id: 'ice-moveset-v1-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'ice-moveset-v1-v': { id: 'ice-moveset-v1-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'ice-moveset-v2-z': { id: 'ice-moveset-v2-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'ice-moveset-v2-x': { id: 'ice-moveset-v2-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'ice-moveset-v2-c': { id: 'ice-moveset-v2-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'ice-moveset-v2-v': { id: 'ice-moveset-v2-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'ice-moveset-v2-f': { id: 'ice-moveset-v2-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'sand-moveset-v1-z': { id: 'sand-moveset-v1-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'sand-moveset-v1-x': { id: 'sand-moveset-v1-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'sand-moveset-v1-c': { id: 'sand-moveset-v1-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'sand-moveset-v1-v': { id: 'sand-moveset-v1-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'sand-moveset-v1-f': { id: 'sand-moveset-v1-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'sand-moveset-v2-z': { id: 'sand-moveset-v2-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'sand-moveset-v2-x': { id: 'sand-moveset-v2-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'sand-moveset-v2-c': { id: 'sand-moveset-v2-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'sand-moveset-v2-v': { id: 'sand-moveset-v2-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'sand-moveset-v2-f': { id: 'sand-moveset-v2-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'dark-moveset-v1-z': { id: 'dark-moveset-v1-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'dark-moveset-v1-x': { id: 'dark-moveset-v1-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'dark-moveset-v1-c': { id: 'dark-moveset-v1-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'dark-moveset-v1-v': { id: 'dark-moveset-v1-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'dark-moveset-v2-z': { id: 'dark-moveset-v2-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'dark-moveset-v2-x': { id: 'dark-moveset-v2-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'dark-moveset-v2-c': { id: 'dark-moveset-v2-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'dark-moveset-v2-v': { id: 'dark-moveset-v2-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'dark-moveset-v2-f': { id: 'dark-moveset-v2-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'eagle-moveset-z': { id: 'eagle-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'eagle-moveset-x': { id: 'eagle-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'eagle-moveset-c': { id: 'eagle-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'eagle-moveset-v': { id: 'eagle-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'eagle-moveset-f': { id: 'eagle-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'diamond-moveset-z': { id: 'diamond-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'diamond-moveset-x': { id: 'diamond-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'diamond-moveset-c': { id: 'diamond-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'diamond-moveset-v': { id: 'diamond-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'light-moveset-v1-z': { id: 'light-moveset-v1-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'light-moveset-v1-x': { id: 'light-moveset-v1-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'light-moveset-v1-c': { id: 'light-moveset-v1-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'light-moveset-v1-v': { id: 'light-moveset-v1-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'light-moveset-v1-f': { id: 'light-moveset-v1-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'light-moveset-v2-z': { id: 'light-moveset-v2-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'light-moveset-v2-x': { id: 'light-moveset-v2-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'light-moveset-v2-c': { id: 'light-moveset-v2-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'light-moveset-v2-v': { id: 'light-moveset-v2-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'light-moveset-v2-f': { id: 'light-moveset-v2-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'rubber-moveset-z': { id: 'rubber-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'rubber-moveset-x': { id: 'rubber-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'rubber-moveset-c': { id: 'rubber-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'rubber-moveset-v': { id: 'rubber-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'rubber-moveset-f': { id: 'rubber-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'rubber-moveset-transformed-z': { id: 'rubber-moveset-transformed-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'rubber-moveset-transformed-x': { id: 'rubber-moveset-transformed-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'rubber-moveset-transformed-c': { id: 'rubber-moveset-transformed-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'rubber-moveset-transformed-v': { id: 'rubber-moveset-transformed-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'rubber-moveset-transformed-f': { id: 'rubber-moveset-transformed-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'ghost-moveset-z': { id: 'ghost-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'ghost-moveset-x': { id: 'ghost-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'ghost-moveset-c': { id: 'ghost-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'ghost-moveset-v': { id: 'ghost-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'ghost-moveset-f': { id: 'ghost-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'magma-moveset-v1-z': { id: 'magma-moveset-v1-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'magma-moveset-v1-x': { id: 'magma-moveset-v1-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'magma-moveset-v1-c': { id: 'magma-moveset-v1-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'magma-moveset-v1-v': { id: 'magma-moveset-v1-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'magma-moveset-v1-f': { id: 'magma-moveset-v1-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'magma-moveset-v2-z': { id: 'magma-moveset-v2-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'magma-moveset-v2-x': { id: 'magma-moveset-v2-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'magma-moveset-v2-c': { id: 'magma-moveset-v2-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'magma-moveset-v2-v': { id: 'magma-moveset-v2-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'magma-moveset-v2-f': { id: 'magma-moveset-v2-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'quake-moveset-v2-z': { id: 'quake-moveset-v2-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'quake-moveset-v2-x': { id: 'quake-moveset-v2-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'quake-moveset-v2-c': { id: 'quake-moveset-v2-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'quake-moveset-v2-v': { id: 'quake-moveset-v2-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'buddha-moveset-v1-z': { id: 'buddha-moveset-v1-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'buddha-moveset-v1-x': { id: 'buddha-moveset-v1-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'buddha-moveset-v1-c': { id: 'buddha-moveset-v1-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'buddha-moveset-v1-v': { id: 'buddha-moveset-v1-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'buddha-moveset-v2-z': { id: 'buddha-moveset-v2-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'buddha-moveset-v2-x': { id: 'buddha-moveset-v2-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'buddha-moveset-v2-c': { id: 'buddha-moveset-v2-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'buddha-moveset-v2-v': { id: 'buddha-moveset-v2-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'buddha-moveset-v2-f': { id: 'buddha-moveset-v2-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'love-base-z': { id: 'love-base-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'love-base-x': { id: 'love-base-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'love-base-c': { id: 'love-base-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'love-base-v': { id: 'love-base-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'love-base-f': { id: 'love-base-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'creation-moveset-z': { id: 'creation-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'creation-moveset-x': { id: 'creation-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'creation-moveset-c': { id: 'creation-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'creation-moveset-v': { id: 'creation-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'creation-moveset-f': { id: 'creation-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'spider-base-z': { id: 'spider-base-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'spider-base-x': { id: 'spider-base-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'spider-base-c': { id: 'spider-base-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'spider-base-v': { id: 'spider-base-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'spider-base-f': { id: 'spider-base-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'sound-moveset-z': { id: 'sound-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'sound-moveset-x': { id: 'sound-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'sound-moveset-c': { id: 'sound-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'sound-moveset-v': { id: 'sound-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'sound-moveset-f': { id: 'sound-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'phoenix-moveset-v1-z': { id: 'phoenix-moveset-v1-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'phoenix-moveset-v1-x': { id: 'phoenix-moveset-v1-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'phoenix-moveset-v1-c': { id: 'phoenix-moveset-v1-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'phoenix-moveset-v1-v': { id: 'phoenix-moveset-v1-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'phoenix-moveset-v1-f': { id: 'phoenix-moveset-v1-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'phoenix-moveset-v2-z': { id: 'phoenix-moveset-v2-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'phoenix-moveset-v2-x': { id: 'phoenix-moveset-v2-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'phoenix-moveset-v2-c': { id: 'phoenix-moveset-v2-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'phoenix-moveset-v2-v': { id: 'phoenix-moveset-v2-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'phoenix-moveset-v2-f': { id: 'phoenix-moveset-v2-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'portal-base-m1': { id: 'portal-base-m1', slot: 'M1', cooldownMs: 1200, mpCost: 4 },
  'portal-base-z': { id: 'portal-base-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'portal-base-x': { id: 'portal-base-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'portal-base-c': { id: 'portal-base-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'portal-base-v': { id: 'portal-base-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'portal-base-f': { id: 'portal-base-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'lightning-moveset-z': { id: 'lightning-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'lightning-moveset-x': { id: 'lightning-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'lightning-moveset-c': { id: 'lightning-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'lightning-moveset-v': { id: 'lightning-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'lightning-moveset-f': { id: 'lightning-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'pain-moveset-z': { id: 'pain-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'pain-moveset-x': { id: 'pain-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'pain-moveset-c': { id: 'pain-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'pain-moveset-v': { id: 'pain-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'pain-moveset-f': { id: 'pain-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'blizzard-moveset-z': { id: 'blizzard-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'blizzard-moveset-x': { id: 'blizzard-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'blizzard-moveset-c': { id: 'blizzard-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'blizzard-moveset-v': { id: 'blizzard-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'blizzard-moveset-f': { id: 'blizzard-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'gravity-moveset-z': { id: 'gravity-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'gravity-moveset-x': { id: 'gravity-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'gravity-moveset-c': { id: 'gravity-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'gravity-moveset-v': { id: 'gravity-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'gravity-moveset-f': { id: 'gravity-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'mammoth-moveset-z': { id: 'mammoth-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'mammoth-moveset-x': { id: 'mammoth-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'mammoth-moveset-c': { id: 'mammoth-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'mammoth-moveset-v': { id: 'mammoth-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'mammoth-moveset-f': { id: 'mammoth-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'mammoth-moveset-transformed-z': { id: 'mammoth-moveset-transformed-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'mammoth-moveset-transformed-x': { id: 'mammoth-moveset-transformed-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'mammoth-moveset-transformed-c': { id: 'mammoth-moveset-transformed-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'mammoth-moveset-transformed-v': { id: 'mammoth-moveset-transformed-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'mammoth-moveset-transformed-f': { id: 'mammoth-moveset-transformed-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  't-rex-moveset-z': { id: 't-rex-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  't-rex-moveset-x': { id: 't-rex-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  't-rex-moveset-c': { id: 't-rex-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  't-rex-moveset-v': { id: 't-rex-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  't-rex-moveset-f': { id: 't-rex-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  't-rex-moveset-transformed-z': { id: 't-rex-moveset-transformed-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  't-rex-moveset-transformed-x': { id: 't-rex-moveset-transformed-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  't-rex-moveset-transformed-c': { id: 't-rex-moveset-transformed-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  't-rex-moveset-transformed-v': { id: 't-rex-moveset-transformed-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  't-rex-moveset-transformed-f': { id: 't-rex-moveset-transformed-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'dough-moveset-v1-z': { id: 'dough-moveset-v1-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'dough-moveset-v1-x': { id: 'dough-moveset-v1-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'dough-moveset-v1-c': { id: 'dough-moveset-v1-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'dough-moveset-v1-v': { id: 'dough-moveset-v1-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'dough-moveset-v1-f': { id: 'dough-moveset-v1-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'dough-moveset-v2-m1': { id: 'dough-moveset-v2-m1', slot: 'M1', cooldownMs: 1200, mpCost: 4 },
  'dough-moveset-v2-z': { id: 'dough-moveset-v2-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'dough-moveset-v2-x': { id: 'dough-moveset-v2-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'dough-moveset-v2-c': { id: 'dough-moveset-v2-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'dough-moveset-v2-v': { id: 'dough-moveset-v2-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'dough-moveset-v2-f': { id: 'dough-moveset-v2-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'shadow-moveset-z': { id: 'shadow-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'shadow-moveset-x': { id: 'shadow-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'shadow-moveset-c': { id: 'shadow-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'shadow-moveset-v': { id: 'shadow-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'shadow-moveset-f': { id: 'shadow-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'venom-moveset-transformed-z': { id: 'venom-moveset-transformed-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'venom-moveset-transformed-x': { id: 'venom-moveset-transformed-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'venom-moveset-transformed-c': { id: 'venom-moveset-transformed-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'venom-moveset-transformed-v': { id: 'venom-moveset-transformed-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'venom-moveset-transformed-f': { id: 'venom-moveset-transformed-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'gas-moveset-z': { id: 'gas-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'gas-moveset-x': { id: 'gas-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'gas-moveset-c': { id: 'gas-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'gas-moveset-v': { id: 'gas-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'gas-moveset-f': { id: 'gas-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'spirit-moveset-m1': { id: 'spirit-moveset-m1', slot: 'M1', cooldownMs: 1200, mpCost: 4 },
  'spirit-moveset-z': { id: 'spirit-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'spirit-moveset-x': { id: 'spirit-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'spirit-moveset-c': { id: 'spirit-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'spirit-moveset-v': { id: 'spirit-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'spirit-moveset-f': { id: 'spirit-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'tiger-moveset-z': { id: 'tiger-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'tiger-moveset-x': { id: 'tiger-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'tiger-moveset-c': { id: 'tiger-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'tiger-moveset-v': { id: 'tiger-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'tiger-moveset-f': { id: 'tiger-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'yeti-moveset-z': { id: 'yeti-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'yeti-moveset-x': { id: 'yeti-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'yeti-moveset-c': { id: 'yeti-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'yeti-moveset-v': { id: 'yeti-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'yeti-moveset-f': { id: 'yeti-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'yeti-moveset-transformed-z': { id: 'yeti-moveset-transformed-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'yeti-moveset-transformed-x': { id: 'yeti-moveset-transformed-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'yeti-moveset-transformed-c': { id: 'yeti-moveset-transformed-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'yeti-moveset-transformed-v': { id: 'yeti-moveset-transformed-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'yeti-moveset-transformed-f': { id: 'yeti-moveset-transformed-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'kitsune-moveset-z': { id: 'kitsune-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'kitsune-moveset-x': { id: 'kitsune-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'kitsune-moveset-c': { id: 'kitsune-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'kitsune-moveset-v': { id: 'kitsune-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'kitsune-moveset-f': { id: 'kitsune-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'kitsune-moveset-transformed-z': { id: 'kitsune-moveset-transformed-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'kitsune-moveset-transformed-x': { id: 'kitsune-moveset-transformed-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'kitsune-moveset-transformed-c': { id: 'kitsune-moveset-transformed-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'kitsune-moveset-transformed-v': { id: 'kitsune-moveset-transformed-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'kitsune-moveset-transformed-f': { id: 'kitsune-moveset-transformed-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'control-moveset-z': { id: 'control-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'control-moveset-x': { id: 'control-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'control-moveset-c': { id: 'control-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'control-moveset-f': { id: 'control-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'control-moveset-v': { id: 'control-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'dragon-moveset-z': { id: 'dragon-moveset-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'dragon-moveset-x': { id: 'dragon-moveset-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'dragon-moveset-c': { id: 'dragon-moveset-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'dragon-moveset-v': { id: 'dragon-moveset-v', slot: 'V', cooldownMs: 20000, mpCost: 50 },
  'dragon-moveset-f': { id: 'dragon-moveset-f', slot: 'F', cooldownMs: 4000, mpCost: 10 },
  'bisento-v1-z': { id: 'bisento-v1-z', slot: 'Z', cooldownMs: 9000, mpCost: 20 },
  'bisento-v1-x': { id: 'bisento-v1-x', slot: 'X', cooldownMs: 13500, mpCost: 30 },
  'bisento-v2-z': { id: 'bisento-v2-z', slot: 'Z', cooldownMs: 9000, mpCost: 20 },
  'bisento-v2-x': { id: 'bisento-v2-x', slot: 'X', cooldownMs: 13500, mpCost: 30 },
  'buddy-sword-z': { id: 'buddy-sword-z', slot: 'Z', cooldownMs: 9000, mpCost: 20 },
  'buddy-sword-x': { id: 'buddy-sword-x', slot: 'X', cooldownMs: 13500, mpCost: 40 },
  'canvander-z': { id: 'canvander-z', slot: 'Z', cooldownMs: 9000, mpCost: 20 },
  'canvander-x': { id: 'canvander-x', slot: 'X', cooldownMs: 13500, mpCost: 30 },
  'cursed-dual-katana-z': { id: 'cursed-dual-katana-z', slot: 'Z', cooldownMs: 9000, mpCost: 30 },
  'cursed-dual-katana-x': { id: 'cursed-dual-katana-x', slot: 'X', cooldownMs: 14000, mpCost: 60 },
  'cutlass-z': { id: 'cutlass-z', slot: 'Z', cooldownMs: 7000, mpCost: 15 },
  'cutlass-x': { id: 'cutlass-x', slot: 'X', cooldownMs: 10000, mpCost: 25 },
  'dark-blade-v1-z': { id: 'dark-blade-v1-z', slot: 'Z', cooldownMs: 8500, mpCost: 20 },
  'dark-blade-v1-x': { id: 'dark-blade-v1-x', slot: 'X', cooldownMs: 13000, mpCost: 40 },
  'dark-blade-v2-z': { id: 'dark-blade-v2-z', slot: 'Z', cooldownMs: 8500, mpCost: 20 },
  'dark-blade-v2-x': { id: 'dark-blade-v2-x', slot: 'X', cooldownMs: 13000, mpCost: 40 },
  'dark-blade-v3-z': { id: 'dark-blade-v3-z', slot: 'Z', cooldownMs: 8500, mpCost: 20 },
  'dark-blade-v3-x': { id: 'dark-blade-v3-x', slot: 'X', cooldownMs: 13000, mpCost: 40 },
  'dark-dagger-z': { id: 'dark-dagger-z', slot: 'Z', cooldownMs: 9500, mpCost: 20 },
  'dark-dagger-x': { id: 'dark-dagger-x', slot: 'X', cooldownMs: 13500, mpCost: 40 },
  'dragon-trident-z': { id: 'dragon-trident-z', slot: 'Z', cooldownMs: 9000, mpCost: 30 },
  'dragon-trident-x': { id: 'dragon-trident-x', slot: 'X', cooldownMs: 13500, mpCost: 60 },
  'dragonheart-z': { id: 'dragonheart-z', slot: 'Z', cooldownMs: 9000, mpCost: 30 },
  'dragonheart-x': { id: 'dragonheart-x', slot: 'X', cooldownMs: 13500, mpCost: 60 },
  'dual-katana-z': { id: 'dual-katana-z', slot: 'Z', cooldownMs: 7000, mpCost: 15 },
  'dual-katana-x': { id: 'dual-katana-x', slot: 'X', cooldownMs: 13000, mpCost: 25 },
  'dual-headed-blade-z': { id: 'dual-headed-blade-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'dual-headed-blade-x': { id: 'dual-headed-blade-x', slot: 'X', cooldownMs: 10000, mpCost: 25 },
  'flail-z': { id: 'flail-z', slot: 'Z', cooldownMs: 9000, mpCost: 16 },
  'flail-x': { id: 'flail-x', slot: 'X', cooldownMs: 12000, mpCost: 24 },
  'fox-lamp-z': { id: 'fox-lamp-z', slot: 'Z', cooldownMs: 10000, mpCost: 30 },
  'fox-lamp-x': { id: 'fox-lamp-x', slot: 'X', cooldownMs: 13000, mpCost: 60 },
  'gravity-blade-z': { id: 'gravity-blade-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'gravity-blade-x': { id: 'gravity-blade-x', slot: 'X', cooldownMs: 10500, mpCost: 25 },
  'hallow-scythe-z': { id: 'hallow-scythe-z', slot: 'Z', cooldownMs: 9000, mpCost: 30 },
  'hallow-scythe-x': { id: 'hallow-scythe-x', slot: 'X', cooldownMs: 13000, mpCost: 60 },
  'iron-mace-z': { id: 'iron-mace-z', slot: 'Z', cooldownMs: 7000, mpCost: 16 },
  'iron-mace-x': { id: 'iron-mace-x', slot: 'X', cooldownMs: 11000, mpCost: 24 },
  'katana-z': { id: 'katana-z', slot: 'Z', cooldownMs: 7000, mpCost: 15 },
  'katana-x': { id: 'katana-x', slot: 'X', cooldownMs: 10000, mpCost: 25 },
  'koko-z': { id: 'koko-z', slot: 'Z', cooldownMs: 9000, mpCost: 16 },
  'koko-x': { id: 'koko-x', slot: 'X', cooldownMs: 13500, mpCost: 24 },
  'longsword-z': { id: 'longsword-z', slot: 'Z', cooldownMs: 8000, mpCost: 16 },
  'longsword-x': { id: 'longsword-x', slot: 'X', cooldownMs: 13000, mpCost: 24 },
  'midnight-blade-z': { id: 'midnight-blade-z', slot: 'Z', cooldownMs: 7000, mpCost: 30 },
  'midnight-blade-x': { id: 'midnight-blade-x', slot: 'X', cooldownMs: 10000, mpCost: 60 },
  'oroshi-z': { id: 'oroshi-z', slot: 'Z', cooldownMs: 8000, mpCost: 20 },
  'oroshi-x': { id: 'oroshi-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'pipe-z': { id: 'pipe-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'pipe-x': { id: 'pipe-x', slot: 'X', cooldownMs: 10500, mpCost: 25 },
  'pole-1st-form-z': { id: 'pole-1st-form-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'pole-1st-form-x': { id: 'pole-1st-form-x', slot: 'X', cooldownMs: 10500, mpCost: 25 },
  'pole-2nd-form-z': { id: 'pole-2nd-form-z', slot: 'Z', cooldownMs: 9000, mpCost: 30 },
  'pole-2nd-form-x': { id: 'pole-2nd-form-x', slot: 'X', cooldownMs: 13500, mpCost: 60 },
  'rengoku-z': { id: 'rengoku-z', slot: 'Z', cooldownMs: 9000, mpCost: 20 },
  'rengoku-x': { id: 'rengoku-x', slot: 'X', cooldownMs: 13500, mpCost: 30 },
  'saber-v1-z': { id: 'saber-v1-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'saber-v1-x': { id: 'saber-v1-x', slot: 'X', cooldownMs: 14000, mpCost: 30 },
  'saber-v2-z': { id: 'saber-v2-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'saber-v2-x': { id: 'saber-v2-x', slot: 'X', cooldownMs: 14000, mpCost: 30 },
  'saishi-z': { id: 'saishi-z', slot: 'Z', cooldownMs: 8000, mpCost: 20 },
  'saishi-x': { id: 'saishi-x', slot: 'X', cooldownMs: 13000, mpCost: 30 },
  'shark-anchor-z': { id: 'shark-anchor-z', slot: 'Z', cooldownMs: 9000, mpCost: 30 },
  'shark-anchor-x': { id: 'shark-anchor-x', slot: 'X', cooldownMs: 13500, mpCost: 60 },
  'shark-saw-z': { id: 'shark-saw-z', slot: 'Z', cooldownMs: 8000, mpCost: 15 },
  'shark-saw-x': { id: 'shark-saw-x', slot: 'X', cooldownMs: 12000, mpCost: 25 },
  'shizu-z': { id: 'shizu-z', slot: 'Z', cooldownMs: 9000, mpCost: 20 },
  'shizu-x': { id: 'shizu-x', slot: 'X', cooldownMs: 13500, mpCost: 30 },
  'soul-cane-z': { id: 'soul-cane-z', slot: 'Z', cooldownMs: 7500, mpCost: 25 },
  'soul-cane-x': { id: 'soul-cane-x', slot: 'X', cooldownMs: 13500, mpCost: 30 },
  'spikey-trident-z': { id: 'spikey-trident-z', slot: 'Z', cooldownMs: 9000, mpCost: 20 },
  'spikey-trident-x': { id: 'spikey-trident-x', slot: 'X', cooldownMs: 13500, mpCost: 40 },
  'trident-z': { id: 'trident-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'trident-x': { id: 'trident-x', slot: 'X', cooldownMs: 11000, mpCost: 24 },
  'triple-dark-blade-z': { id: 'triple-dark-blade-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'triple-dark-blade-x': { id: 'triple-dark-blade-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'triple-katana-z': { id: 'triple-katana-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'triple-katana-x': { id: 'triple-katana-x', slot: 'X', cooldownMs: 12000, mpCost: 25 },
  'true-triple-katana-z': { id: 'true-triple-katana-z', slot: 'Z', cooldownMs: 8000, mpCost: 30 },
  'true-triple-katana-x': { id: 'true-triple-katana-x', slot: 'X', cooldownMs: 13000, mpCost: 60 },
  'tushita-z': { id: 'tushita-z', slot: 'Z', cooldownMs: 9000, mpCost: 15 },
  'tushita-x': { id: 'tushita-x', slot: 'X', cooldownMs: 14000, mpCost: 30 },
  'twin-hooks-z': { id: 'twin-hooks-z', slot: 'Z', cooldownMs: 9000, mpCost: 16 },
  'twin-hooks-x': { id: 'twin-hooks-x', slot: 'X', cooldownMs: 14000, mpCost: 24 },
  'wardens-sword-z': { id: 'wardens-sword-z', slot: 'Z', cooldownMs: 9000, mpCost: 15 },
  'wardens-sword-x': { id: 'wardens-sword-x', slot: 'X', cooldownMs: 15000, mpCost: 25 },
  'yama-z': { id: 'yama-z', slot: 'Z', cooldownMs: 9000, mpCost: 20 },
  'yama-x': { id: 'yama-x', slot: 'X', cooldownMs: 14000, mpCost: 30 },
  'acidum-rifle-z': { id: 'acidum-rifle-z', slot: 'Z', cooldownMs: 10000, mpCost: 30 },
  'acidum-rifle-x': { id: 'acidum-rifle-x', slot: 'X', cooldownMs: 15750, mpCost: 60 },
  'bazooka-z': { id: 'bazooka-z', slot: 'Z', cooldownMs: 14000, mpCost: 50 },
  'bazooka-x': { id: 'bazooka-x', slot: 'X', cooldownMs: 22000, mpCost: 80 },
  'bizarre-revolver-z': { id: 'bizarre-revolver-z', slot: 'Z', cooldownMs: 9500, mpCost: 30 },
  'bizarre-revolver-x': { id: 'bizarre-revolver-x', slot: 'X', cooldownMs: 27000, mpCost: 60 },
  'bizarre-rifle-z': { id: 'bizarre-rifle-z', slot: 'Z', cooldownMs: 9000, mpCost: 16 },
  'bizarre-rifle-x': { id: 'bizarre-rifle-x', slot: 'X', cooldownMs: 15000, mpCost: 24 },
  'cannon-z': { id: 'cannon-z', slot: 'Z', cooldownMs: 11000, mpCost: 35 },
  'cannon-x': { id: 'cannon-x', slot: 'X', cooldownMs: 16000, mpCost: 50 },
  'dragonstorm-z': { id: 'dragonstorm-z', slot: 'Z', cooldownMs: 9000, mpCost: 20 },
  'dragonstorm-x': { id: 'dragonstorm-x', slot: 'X', cooldownMs: 15000, mpCost: 60 },
  'dual-flintlock-z': { id: 'dual-flintlock-z', slot: 'Z', cooldownMs: 11000, mpCost: 40 },
  'dual-flintlock-x': { id: 'dual-flintlock-x', slot: 'X', cooldownMs: 28000, mpCost: 60 },
  'flintlock-z': { id: 'flintlock-z', slot: 'Z', cooldownMs: 9000, mpCost: 30 },
  'flintlock-x': { id: 'flintlock-x', slot: 'X', cooldownMs: 15000, mpCost: 50 },
  'kabucha-z': { id: 'kabucha-z', slot: 'Z', cooldownMs: 9000, mpCost: 20 },
  'kabucha-x': { id: 'kabucha-x', slot: 'X', cooldownMs: 15000, mpCost: 60 },
  'magma-blaster-z': { id: 'magma-blaster-z', slot: 'Z', cooldownMs: 9000, mpCost: 30 },
  'magma-blaster-x': { id: 'magma-blaster-x', slot: 'X', cooldownMs: 18000, mpCost: 60 },
  'musket-z': { id: 'musket-z', slot: 'Z', cooldownMs: 9000, mpCost: 20 },
  'musket-x': { id: 'musket-x', slot: 'X', cooldownMs: 19000, mpCost: 40 },
  'refined-flintlock-z': { id: 'refined-flintlock-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'refined-flintlock-x': { id: 'refined-flintlock-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'refined-musket-z': { id: 'refined-musket-z', slot: 'Z', cooldownMs: 9000, mpCost: 16 },
  'refined-musket-x': { id: 'refined-musket-x', slot: 'X', cooldownMs: 19000, mpCost: 24 },
  'refined-slingshot-z': { id: 'refined-slingshot-z', slot: 'Z', cooldownMs: 10500, mpCost: 20 },
  'refined-slingshot-x': { id: 'refined-slingshot-x', slot: 'X', cooldownMs: 13500, mpCost: 40 },
  'skull-guitar-z': { id: 'skull-guitar-z', slot: 'Z', cooldownMs: 10000, mpCost: 20 },
  'skull-guitar-x': { id: 'skull-guitar-x', slot: 'X', cooldownMs: 14000, mpCost: 40 },
  'slingshot-z': { id: 'slingshot-z', slot: 'Z', cooldownMs: 11000, mpCost: 20 },
  'slingshot-x': { id: 'slingshot-x', slot: 'X', cooldownMs: 14000, mpCost: 40 },
  'venom-bow-z': { id: 'venom-bow-z', slot: 'Z', cooldownMs: 9000, mpCost: 20 },
  'venom-bow-x': { id: 'venom-bow-x', slot: 'X', cooldownMs: 15000, mpCost: 60 },
  'combat-z': { id: 'combat-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'combat-x': { id: 'combat-x', slot: 'X', cooldownMs: 12000, mpCost: 25 },
  'combat-c': { id: 'combat-c', slot: 'C', cooldownMs: 14000, mpCost: 30 },
  'combat-v': { id: 'combat-v', slot: 'V', cooldownMs: 22000, mpCost: 60 },
  'dark-step-z': { id: 'dark-step-z', slot: 'Z', cooldownMs: 10000, mpCost: 15 },
  'dark-step-x': { id: 'dark-step-x', slot: 'X', cooldownMs: 15000, mpCost: 25 },
  'dark-step-c': { id: 'dark-step-c', slot: 'C', cooldownMs: 20000, mpCost: 55 },
  'dark-step-v': { id: 'dark-step-v', slot: 'V', cooldownMs: 90000, mpCost: 100 },
  'electric-z': { id: 'electric-z', slot: 'Z', cooldownMs: 6000, mpCost: 20 },
  'electric-x': { id: 'electric-x', slot: 'X', cooldownMs: 10000, mpCost: 30 },
  'electric-c': { id: 'electric-c', slot: 'C', cooldownMs: 15000, mpCost: 60 },
  'water-kung-fu-z': { id: 'water-kung-fu-z', slot: 'Z', cooldownMs: 6000, mpCost: 16 },
  'water-kung-fu-x': { id: 'water-kung-fu-x', slot: 'X', cooldownMs: 10000, mpCost: 24 },
  'water-kung-fu-c': { id: 'water-kung-fu-c', slot: 'C', cooldownMs: 15000, mpCost: 32 },
  'death-step-z': { id: 'death-step-z', slot: 'Z', cooldownMs: 7500, mpCost: 15 },
  'death-step-x': { id: 'death-step-x', slot: 'X', cooldownMs: 10500, mpCost: 25 },
  'death-step-c': { id: 'death-step-c', slot: 'C', cooldownMs: 16500, mpCost: 55 },
  'death-step-v': { id: 'death-step-v', slot: 'V', cooldownMs: 90000, mpCost: 100 },
  'electric-claw-z': { id: 'electric-claw-z', slot: 'Z', cooldownMs: 8000, mpCost: 30 },
  'electric-claw-x': { id: 'electric-claw-x', slot: 'X', cooldownMs: 11000, mpCost: 40 },
  'electric-claw-c': { id: 'electric-claw-c', slot: 'C', cooldownMs: 17000, mpCost: 75 },
  'sharkman-karate-z': { id: 'sharkman-karate-z', slot: 'Z', cooldownMs: 7000, mpCost: 30 },
  'sharkman-karate-x': { id: 'sharkman-karate-x', slot: 'X', cooldownMs: 11000, mpCost: 40 },
  'sharkman-karate-c': { id: 'sharkman-karate-c', slot: 'C', cooldownMs: 16000, mpCost: 75 },
  'dragon-breath-z': { id: 'dragon-breath-z', slot: 'Z', cooldownMs: 7000, mpCost: 25 },
  'dragon-breath-x': { id: 'dragon-breath-x', slot: 'X', cooldownMs: 10000, mpCost: 35 },
  'dragon-breath-c': { id: 'dragon-breath-c', slot: 'C', cooldownMs: 16000, mpCost: 70 },
  'superhuman-z': { id: 'superhuman-z', slot: 'Z', cooldownMs: 7000, mpCost: 25 },
  'superhuman-x': { id: 'superhuman-x', slot: 'X', cooldownMs: 9000, mpCost: 24 },
  'superhuman-c': { id: 'superhuman-c', slot: 'C', cooldownMs: 12000, mpCost: 32 },
  'dragon-talon-z': { id: 'dragon-talon-z', slot: 'Z', cooldownMs: 7500, mpCost: 30 },
  'dragon-talon-x': { id: 'dragon-talon-x', slot: 'X', cooldownMs: 10000, mpCost: 40 },
  'dragon-talon-c': { id: 'dragon-talon-c', slot: 'C', cooldownMs: 17000, mpCost: 75 },
  'godhuman-z': { id: 'godhuman-z', slot: 'Z', cooldownMs: 8000, mpCost: 25 },
  'godhuman-x': { id: 'godhuman-x', slot: 'X', cooldownMs: 11000, mpCost: 35 },
  'godhuman-c': { id: 'godhuman-c', slot: 'C', cooldownMs: 17000, mpCost: 75 },
  'sanguine-art-z': { id: 'sanguine-art-z', slot: 'Z', cooldownMs: 8000, mpCost: 20 },
  'sanguine-art-x': { id: 'sanguine-art-x', slot: 'X', cooldownMs: 11000, mpCost: 30 },
  'sanguine-art-c': { id: 'sanguine-art-c', slot: 'C', cooldownMs: 18000, mpCost: 75 },
};

export const SKILL_MASTERY_REQUIRED: Readonly<Record<string, number>> = {
  'acidum-rifle-x': 200,
  'acidum-rifle-z': 100,
  'bazooka-x': 250,
  'bazooka-z': 100,
  'bisento-v1-x': 150,
  'bisento-v1-z': 50,
  'bisento-v2-x': 150,
  'bisento-v2-z': 50,
  'bizarre-revolver-x': 300,
  'bizarre-revolver-z': 150,
  'bizarre-rifle-x': 300,
  'bizarre-rifle-z': 150,
  'blade-base-c': 50,
  'blade-base-f': 80,
  'blade-base-m1': 1,
  'blade-base-x': 20,
  'blizzard-moveset-c': 160,
  'blizzard-moveset-f': 40,
  'blizzard-moveset-v': 250,
  'blizzard-moveset-x': 90,
  'blizzard-moveset-z': 1,
  'bomb-base-c': 75,
  'bomb-base-f': 25,
  'bomb-base-m1': 1,
  'bomb-base-v': 125,
  'bomb-base-x': 50,
  'bomb-base-z': 1,
  'buddha-moveset-v1-c': 100,
  'buddha-moveset-v1-v': 200,
  'buddha-moveset-v1-x': 1,
  'buddha-moveset-v1-z': 1,
  'buddha-moveset-v2-c': 100,
  'buddha-moveset-v2-f': 0,
  'buddha-moveset-v2-v': 200,
  'buddha-moveset-v2-x': 1,
  'buddha-moveset-v2-z': 1,
  'buddy-sword-z': 150,
  'cannon-x': 100,
  'cannon-z': 40,
  'canvander-x': 300,
  'combat-c': 50,
  'combat-v': 150,
  'combat-x': 20,
  'combat-z': 1,
  'control-moveset-c': 250,
  'control-moveset-f': 75,
  'control-moveset-v': 350,
  'control-moveset-x': 150,
  'control-moveset-z': 1,
  'creation-moveset-c': 90,
  'creation-moveset-f': 10,
  'creation-moveset-v': 130,
  'creation-moveset-x': 45,
  'creation-moveset-z': 1,
  'cursed-dual-katana-x': 375,
  'cursed-dual-katana-z': 175,
  'cutlass-x': 20,
  'cutlass-z': 1,
  'dark-blade-v1-x': 50,
  'dark-blade-v1-z': 1,
  'dark-blade-v2-x': 50,
  'dark-blade-v2-z': 1,
  'dark-blade-v3-x': 50,
  'dark-blade-v3-z': 1,
  'dark-dagger-x': 300,
  'dark-dagger-z': 150,
  'dark-moveset-v1-c': 80,
  'dark-moveset-v1-v': 110,
  'dark-moveset-v1-x': 40,
  'dark-moveset-v1-z': 1,
  'dark-moveset-v2-c': 80,
  'dark-moveset-v2-f': 0,
  'dark-moveset-v2-v': 110,
  'dark-moveset-v2-x': 40,
  'dark-moveset-v2-z': 1,
  'dark-step-c': 80,
  'dark-step-v': 150,
  'dark-step-x': 40,
  'dark-step-z': 1,
  'death-step-c': 300,
  'death-step-v': 400,
  'death-step-x': 200,
  'death-step-z': 100,
  'diamond-moveset-c': 80,
  'diamond-moveset-v': 110,
  'diamond-moveset-x': 1,
  'diamond-moveset-z': 1,
  'dough-moveset-v1-c': 200,
  'dough-moveset-v1-f': 50,
  'dough-moveset-v1-v': 300,
  'dough-moveset-v1-x': 100,
  'dough-moveset-v1-z': 1,
  'dough-moveset-v2-c': 200,
  'dough-moveset-v2-f': 50,
  'dough-moveset-v2-m1': 1,
  'dough-moveset-v2-v': 300,
  'dough-moveset-v2-x': 100,
  'dragon-breath-c': 300,
  'dragon-breath-x': 200,
  'dragon-breath-z': 100,
  'dragon-moveset-c': 250,
  'dragon-moveset-f': 75,
  'dragon-moveset-v': 350,
  'dragon-moveset-x': 150,
  'dragon-moveset-z': 1,
  'dragon-talon-c': 350,
  'dragon-talon-x': 250,
  'dragon-talon-z': 125,
  'dragon-trident-x': 350,
  'dragon-trident-z': 150,
  'dragonheart-x': 350,
  'dragonheart-z': 150,
  'dragonstorm-x': 250,
  'dragonstorm-z': 125,
  'dual-flintlock-z': 15,
  'dual-headed-blade-x': 100,
  'dual-headed-blade-z': 20,
  'dual-katana-x': 30,
  'dual-katana-z': 1,
  'eagle-moveset-c': 80,
  'eagle-moveset-f': 150,
  'eagle-moveset-v': 110,
  'eagle-moveset-x': 35,
  'eagle-moveset-z': 1,
  'electric-c': 200,
  'electric-claw-c': 330,
  'electric-claw-x': 220,
  'electric-claw-z': 110,
  'electric-x': 100,
  'electric-z': 50,
  'flail-x': 300,
  'flail-z': 150,
  'flame-moveset-v1-c': 50,
  'flame-moveset-v1-f': 10,
  'flame-moveset-v1-v': 100,
  'flame-moveset-v1-x': 25,
  'flame-moveset-v1-z': 1,
  'flame-moveset-v2-c': 50,
  'flame-moveset-v2-f': 10,
  'flame-moveset-v2-v': 100,
  'flame-moveset-v2-x': 25,
  'flame-moveset-v2-z': 1,
  'flintlock-x': 80,
  'fox-lamp-x': 350,
  'fox-lamp-z': 150,
  'gas-moveset-c': 200,
  'gas-moveset-f': 50,
  'gas-moveset-v': 300,
  'gas-moveset-x': 100,
  'gas-moveset-z': 1,
  'ghost-moveset-c': 100,
  'ghost-moveset-f': 75,
  'ghost-moveset-v': 150,
  'ghost-moveset-x': 50,
  'ghost-moveset-z': 1,
  'godhuman-c': 350,
  'godhuman-x': 250,
  'godhuman-z': 125,
  'gravity-blade-x': 250,
  'gravity-blade-z': 125,
  'gravity-moveset-c': 200,
  'gravity-moveset-f': 50,
  'gravity-moveset-v': 300,
  'gravity-moveset-x': 100,
  'gravity-moveset-z': 1,
  'hallow-scythe-x': 350,
  'hallow-scythe-z': 150,
  'ice-moveset-v1-c': 50,
  'ice-moveset-v1-v': 100,
  'ice-moveset-v1-x': 25,
  'ice-moveset-v1-z': 1,
  'ice-moveset-v2-c': 50,
  'ice-moveset-v2-f': 0,
  'ice-moveset-v2-v': 100,
  'ice-moveset-v2-x': 25,
  'ice-moveset-v2-z': 1,
  'iron-mace-z': 1,
  'kabucha-x': 250,
  'kabucha-z': 125,
  'katana-x': 20,
  'kitsune-moveset-c': 100,
  'kitsune-moveset-f': 200,
  'kitsune-moveset-transformed-c': 100,
  'kitsune-moveset-transformed-f': 200,
  'kitsune-moveset-transformed-v': 300,
  'kitsune-moveset-transformed-x': 50,
  'kitsune-moveset-transformed-z': 1,
  'kitsune-moveset-v': 300,
  'kitsune-moveset-x': 50,
  'kitsune-moveset-z': 1,
  'koko-x': 325,
  'koko-z': 150,
  'light-moveset-v1-c': 80,
  'light-moveset-v1-f': 10,
  'light-moveset-v1-v': 110,
  'light-moveset-v1-x': 40,
  'light-moveset-v1-z': 1,
  'light-moveset-v2-c': 80,
  'light-moveset-v2-f': 10,
  'light-moveset-v2-v': 110,
  'light-moveset-v2-x': 40,
  'light-moveset-v2-z': 1,
  'lightning-moveset-c': 160,
  'lightning-moveset-f': 30,
  'lightning-moveset-v': 250,
  'lightning-moveset-x': 90,
  'lightning-moveset-z': 1,
  'longsword-x': 200,
  'longsword-z': 100,
  'love-base-c': 150,
  'love-base-v': 100,
  'love-base-x': 50,
  'love-base-z': 1,
  'magma-blaster-x': 200,
  'magma-blaster-z': 75,
  'magma-moveset-v1-c': 95,
  'magma-moveset-v1-f': 10,
  'magma-moveset-v1-v': 140,
  'magma-moveset-v1-x': 45,
  'magma-moveset-v1-z': 1,
  'magma-moveset-v2-c': 95,
  'magma-moveset-v2-f': 10,
  'magma-moveset-v2-v': 140,
  'magma-moveset-v2-x': 45,
  'magma-moveset-v2-z': 1,
  'mammoth-moveset-c': 100,
  'mammoth-moveset-f': 200,
  'mammoth-moveset-transformed-c': 100,
  'mammoth-moveset-transformed-f': 200,
  'mammoth-moveset-transformed-v': 300,
  'mammoth-moveset-transformed-x': 50,
  'mammoth-moveset-transformed-z': 1,
  'mammoth-moveset-v': 300,
  'mammoth-moveset-x': 50,
  'mammoth-moveset-z': 1,
  'midnight-blade-x': 325,
  'midnight-blade-z': 150,
  'musket-x': 50,
  'musket-z': 20,
  'oroshi-x': 300,
  'oroshi-z': 150,
  'pain-moveset-c': 200,
  'pain-moveset-f': 50,
  'pain-moveset-v': 300,
  'pain-moveset-x': 100,
  'pain-moveset-z': 1,
  'phoenix-moveset-v1-c': 160,
  'phoenix-moveset-v1-f': 30,
  'phoenix-moveset-v1-v': 250,
  'phoenix-moveset-v1-x': 90,
  'phoenix-moveset-v1-z': 1,
  'phoenix-moveset-v2-c': 160,
  'phoenix-moveset-v2-f': 30,
  'phoenix-moveset-v2-v': 250,
  'phoenix-moveset-v2-x': 90,
  'phoenix-moveset-v2-z': 1,
  'pipe-x': 50,
  'pipe-z': 1,
  'pole-1st-form-x': 180,
  'pole-1st-form-z': 80,
  'pole-2nd-form-x': 350,
  'pole-2nd-form-z': 150,
  'portal-base-c': 200,
  'portal-base-f': 100,
  'portal-base-m1': 1,
  'portal-base-v': 300,
  'portal-base-x': 50,
  'quake-moveset-v2-c': 100,
  'quake-moveset-v2-v': 150,
  'quake-moveset-v2-x': 50,
  'quake-moveset-v2-z': 1,
  'refined-flintlock-z': 150,
  'rengoku-x': 350,
  'rengoku-z': 150,
  'rocket-base-c': 50,
  'rocket-base-f': 75,
  'rocket-base-x': 20,
  'rocket-base-z': 1,
  'rubber-moveset-c': 125,
  'rubber-moveset-f': 80,
  'rubber-moveset-transformed-c': 125,
  'rubber-moveset-transformed-f': 80,
  'rubber-moveset-transformed-v': 225,
  'rubber-moveset-transformed-x': 50,
  'rubber-moveset-transformed-z': 25,
  'rubber-moveset-v': 225,
  'rubber-moveset-x': 50,
  'rubber-moveset-z': 25,
  'saber-v1-x': 125,
  'saber-v1-z': 50,
  'saber-v2-x': 125,
  'saber-v2-z': 50,
  'saishi-x': 300,
  'saishi-z': 150,
  'sand-moveset-v1-c': 80,
  'sand-moveset-v1-f': 15,
  'sand-moveset-v1-v': 120,
  'sand-moveset-v1-x': 40,
  'sand-moveset-v1-z': 1,
  'sand-moveset-v2-c': 80,
  'sand-moveset-v2-f': 15,
  'sand-moveset-v2-v': 120,
  'sand-moveset-v2-x': 40,
  'sand-moveset-v2-z': 1,
  'sanguine-art-c': 350,
  'sanguine-art-x': 250,
  'sanguine-art-z': 125,
  'shadow-moveset-c': 200,
  'shadow-moveset-f': 50,
  'shadow-moveset-v': 300,
  'shadow-moveset-x': 100,
  'shadow-moveset-z': 1,
  'shark-anchor-x': 350,
  'shark-anchor-z': 150,
  'shark-saw-x': 60,
  'shark-saw-z': 10,
  'sharkman-karate-c': 300,
  'sharkman-karate-x': 200,
  'sharkman-karate-z': 100,
  'shizu-x': 300,
  'shizu-z': 150,
  'skull-guitar-x': 300,
  'slingshot-x': 40,
  'slingshot-z': 20,
  'smoke-base-c': 50,
  'smoke-base-f': 10,
  'smoke-base-x': 20,
  'smoke-base-z': 1,
  'soul-cane-x': 120,
  'soul-cane-z': 40,
  'sound-moveset-c': 100,
  'sound-moveset-f': 175,
  'sound-moveset-v': 250,
  'sound-moveset-x': 50,
  'sound-moveset-z': 1,
  'spider-base-c': 100,
  'spider-base-f': 15,
  'spider-base-v': 225,
  'spider-base-x': 50,
  'spider-base-z': 1,
  'spike-base-c': 50,
  'spike-base-v': 75,
  'spike-base-x': 25,
  'spike-base-z': 1,
  'spikey-trident-x': 300,
  'spikey-trident-z': 150,
  'spin-base-c': 90,
  'spin-base-f': 25,
  'spin-base-x': 50,
  'spin-base-z': 1,
  'spirit-moveset-c': 250,
  'spirit-moveset-f': 75,
  'spirit-moveset-m1': 1,
  'spirit-moveset-v': 350,
  'spirit-moveset-x': 150,
  'spring-base-c': 50,
  'spring-base-f': 75,
  'spring-base-v': 125,
  'spring-base-x': 20,
  'spring-base-z': 1,
  'superhuman-c': 330,
  'superhuman-x': 220,
  'superhuman-z': 110,
  't-rex-moveset-c': 100,
  't-rex-moveset-f': 200,
  't-rex-moveset-transformed-c': 100,
  't-rex-moveset-transformed-f': 200,
  't-rex-moveset-transformed-v': 300,
  't-rex-moveset-transformed-x': 50,
  't-rex-moveset-transformed-z': 1,
  't-rex-moveset-v': 300,
  't-rex-moveset-x': 50,
  't-rex-moveset-z': 1,
  'tiger-moveset-c': 100,
  'tiger-moveset-f': 200,
  'tiger-moveset-v': 300,
  'tiger-moveset-x': 50,
  'tiger-moveset-z': 1,
  'trident-x': 125,
  'trident-z': 50,
  'triple-dark-blade-x': 50,
  'triple-dark-blade-z': 1,
  'triple-katana-x': 60,
  'triple-katana-z': 20,
  'true-triple-katana-x': 350,
  'true-triple-katana-z': 150,
  'tushita-x': 300,
  'tushita-z': 150,
  'twin-hooks-x': 300,
  'twin-hooks-z': 150,
  'venom-bow-x': 250,
  'venom-bow-z': 125,
  'venom-moveset-transformed-c': 200,
  'venom-moveset-transformed-f': 50,
  'venom-moveset-transformed-v': 300,
  'venom-moveset-transformed-x': 100,
  'venom-moveset-transformed-z': 1,
  'wardens-sword-x': 80,
  'wardens-sword-z': 35,
  'water-kung-fu-c': 250,
  'water-kung-fu-x': 130,
  'water-kung-fu-z': 70,
  'yama-x': 300,
  'yama-z': 150,
  'yeti-moveset-c': 100,
  'yeti-moveset-f': 200,
  'yeti-moveset-transformed-c': 100,
  'yeti-moveset-transformed-f': 200,
  'yeti-moveset-transformed-v': 300,
  'yeti-moveset-transformed-x': 50,
  'yeti-moveset-transformed-z': 1,
  'yeti-moveset-v': 300,
  'yeti-moveset-x': 50,
  'yeti-moveset-z': 1,
};
