import type { GunSkillDefinition } from '../types';

export const GUN_SKILLS: readonly GunSkillDefinition[] = [
  {
    "id": "acidum-rifle-z",
    "gunId": "acidum-rifle",
    "key": "Z",
    "name": "Spiky Bomb",
    "version": "base",
    "mastery": 100,
    "cooldown": 10,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user shoots a green projectile that explodes after a short time, dealing damage and stunning enemies."
  },
  {
    "id": "acidum-rifle-x",
    "gunId": "acidum-rifle",
    "key": "X",
    "name": "Acidic Smoke",
    "version": "base",
    "mastery": 200,
    "cooldown": 15.75,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The user shoots three gas projectiles that deal damage as well as poison damage over time. It also disables the enemy's Instinct. It does not stun, but disables the opponent from attacking, dashing, using Flash Step or using Air Jump for a short duration of time."
  },
  {
    "id": "bazooka-z",
    "gunId": "bazooka",
    "key": "Z",
    "name": "Heat Wave",
    "version": "base",
    "mastery": 100,
    "cooldown": 14,
    "energy": 50,
    "breaksInstinct": true,
    "description": "The user fires a flaming orange beam toward their cursor, damaging and providing knockback toward targets hit, as well as leaving a flaming trail and flames at the end of the beam if it hits a surface. (The flames at the end of the beam last longer)"
  },
  {
    "id": "bazooka-x",
    "gunId": "bazooka",
    "key": "X",
    "name": "Flaring Missiles",
    "version": "base",
    "mastery": 250,
    "cooldown": 22,
    "energy": 80,
    "breaksInstinct": true,
    "description": "The user launches five missiles toward their cursor, which will also seek a target if the target is within range of the missiles. The missiles explode in AoE and leaves a flaming area if they explode near a surface."
  },
  {
    "id": "bizarre-revolver-z",
    "gunId": "bizarre-revolver",
    "key": "Z",
    "name": "Space Bending Blast",
    "version": "base",
    "mastery": 150,
    "cooldown": 9.5,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user shoots a blue, energized bullet towards their cursor. If it is close enough to an enemy, it disappears through a portal before reappearing to the side of the enemy, shooting out and exploding. If it hits an enemy, it stuns them for a short time."
  },
  {
    "id": "bizarre-revolver-x",
    "gunId": "bizarre-revolver",
    "key": "X",
    "name": "Dimensional Surge",
    "version": "base",
    "mastery": 300,
    "cooldown": 27,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The user fires off multiple short, electric blasts coming from many portals in front of the user as an AoE, gaining range as the move is held. This can hit multiple targets, as well as stun them and break Instinct."
  },
  {
    "id": "bizarre-rifle-z",
    "gunId": "bizarre-rifle",
    "key": "Z",
    "name": "Heat-Seeking Shot",
    "version": "base",
    "mastery": 150,
    "cooldown": 9,
    "energy": null,
    "breaksInstinct": false,
    "description": "The user shot a blue ball towards their cursor, which sought an enemy if they are close enough. When hit, the blue ball exploded and stunned for a very short period of time."
  },
  {
    "id": "bizarre-rifle-x",
    "gunId": "bizarre-rifle",
    "key": "X",
    "name": "Hellfire Shower",
    "version": "base",
    "mastery": 300,
    "cooldown": 15,
    "energy": null,
    "breaksInstinct": true,
    "description": "The user shot a burst of four dark blue shots, which dealt damage and left a fire effect similar to Awakened Flame's burning effect, but much stronger and dark blue."
  },
  {
    "id": "cannon-z",
    "gunId": "cannon",
    "key": "Z",
    "name": "Chain Detonation",
    "version": "base",
    "mastery": 40,
    "cooldown": 11,
    "energy": 35,
    "breaksInstinct": false,
    "description": "Fires a long glowing chain which explodes when a target is hit."
  },
  {
    "id": "cannon-x",
    "gunId": "cannon",
    "key": "X",
    "name": "Incendiary Ammo",
    "version": "base",
    "mastery": 100,
    "cooldown": 16,
    "energy": 50,
    "breaksInstinct": false,
    "description": "Shoots three burning cannonballs that explode upon impact. Leaves behind a small pool of flames."
  },
  {
    "id": "dragonstorm-z",
    "gunId": "dragonstorm",
    "key": "Z",
    "name": "Draconic Cascade",
    "version": "base",
    "mastery": 125,
    "cooldown": 9,
    "energy": 20,
    "breaksInstinct": true,
    "description": "This move posseses two distinct variations:"
  },
  {
    "id": "dragonstorm-x",
    "gunId": "dragonstorm",
    "key": "X",
    "name": "Infernal Comet",
    "version": "base",
    "mastery": 250,
    "cooldown": 15,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The player shoots a red fire, dragon-that pulls anyone in its way with it and then explodes into particles upon contact or once it has reached maximum range, leaving flames on the ground after exploding close enough to it. This move deals tick damage to enemies who were hit and pulled by the projectile. It tends to ricochet off of walls."
  },
  {
    "id": "dual-flintlock-z",
    "gunId": "dual-flintlock",
    "key": "Z",
    "name": "Splitting Beam",
    "version": "base",
    "mastery": null,
    "cooldown": 11,
    "energy": 40,
    "breaksInstinct": true,
    "description": ""
  },
  {
    "id": "dual-flintlock-x",
    "gunId": "dual-flintlock",
    "key": "X",
    "name": "Bullet Storm",
    "version": "base",
    "mastery": null,
    "cooldown": 28,
    "energy": 60,
    "breaksInstinct": true,
    "description": ""
  },
  {
    "id": "flintlock-z",
    "gunId": "flintlock",
    "key": "Z",
    "name": "Concentrated Shot",
    "version": "base",
    "mastery": 15,
    "cooldown": 9,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user shoots a bullet. If someone gets hit by the bullet, they will be stunned for a short amount of time and a few bullets split out dealing damage on impact."
  },
  {
    "id": "flintlock-x",
    "gunId": "flintlock",
    "key": "X",
    "name": "Marksman Fury",
    "version": "base",
    "mastery": 80,
    "cooldown": 15,
    "energy": 50,
    "breaksInstinct": true,
    "description": "The user shoots three bullets that explode upon contact. (Cursor impact)"
  },
  {
    "id": "kabucha-z",
    "gunId": "kabucha",
    "key": "Z",
    "name": "Blazing Phoenix",
    "version": "base",
    "mastery": 125,
    "cooldown": 9,
    "energy": 20,
    "breaksInstinct": false,
    "description": "The user fires a flying bird shaped projectile that explodes upon contact and leaves a flame trail behind that deals damage. Anyone hit by this will be launched up in the air."
  },
  {
    "id": "kabucha-x",
    "gunId": "kabucha",
    "key": "X",
    "name": "Dragon Tempest",
    "version": "base",
    "mastery": 250,
    "cooldown": 15,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The user fires a long, cylindrical blast of wind that knocks enemies back, stuns, and breaks Instinct. The knockback for this move is very predictable and the enemy doesn't get flung instantly like with most other attacks. This attack is not single target."
  },
  {
    "id": "magma-blaster-z",
    "gunId": "magma-blaster",
    "key": "Z",
    "name": "Scorching Burst",
    "version": "base",
    "mastery": 75,
    "cooldown": 9,
    "energy": 30,
    "breaksInstinct": true,
    "description": "The user fires a magma bullet that explodes on impact, or when it reaches it's maximum range, scattering molten debris that vanishes shortly after."
  },
  {
    "id": "magma-blaster-x",
    "gunId": "magma-blaster",
    "key": "X",
    "name": "Magmatic Pressure",
    "version": "base",
    "mastery": 200,
    "cooldown": 18,
    "energy": 60,
    "breaksInstinct": true,
    "description": "The user shoots out a beam made out of scorching hot magma that locks and pushes targets away from the user. This move can be held for 2.5 seconds."
  },
  {
    "id": "musket-z",
    "gunId": "musket",
    "key": "Z",
    "name": "Draconic Bullet",
    "version": "base",
    "mastery": 20,
    "cooldown": 9,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user fires an explosive bullet at the target that explodes into smaller homing bullets when it hits. This move is similar to Venom Bow's [Z] Venomous Spit."
  },
  {
    "id": "musket-x",
    "gunId": "musket",
    "key": "X",
    "name": "Torching Shot",
    "version": "base",
    "mastery": 50,
    "cooldown": 19,
    "energy": 40,
    "breaksInstinct": true,
    "description": "The user fires an arrow shaped explosive bullet that creates small AoE damage. This moves is similar to Kabucha's [Z] Blazing Phoenix."
  },
  {
    "id": "refined-flintlock-z",
    "gunId": "refined-flintlock",
    "key": "Z",
    "name": "Disabling Shot",
    "version": "base",
    "mastery": null,
    "cooldown": null,
    "energy": null,
    "breaksInstinct": false,
    "description": ""
  },
  {
    "id": "refined-flintlock-x",
    "gunId": "refined-flintlock",
    "key": "X",
    "name": "Rapid Gun",
    "version": "base",
    "mastery": null,
    "cooldown": null,
    "energy": null,
    "breaksInstinct": false,
    "description": ""
  },
  {
    "id": "refined-musket-z",
    "gunId": "refined-musket",
    "key": "Z",
    "name": "Dragon Bullet",
    "version": "base",
    "mastery": null,
    "cooldown": 9,
    "energy": null,
    "breaksInstinct": false,
    "description": ""
  },
  {
    "id": "refined-musket-x",
    "gunId": "refined-musket",
    "key": "X",
    "name": "Bold Pistolero",
    "version": "base",
    "mastery": null,
    "cooldown": 19,
    "energy": null,
    "breaksInstinct": false,
    "description": ""
  },
  {
    "id": "refined-slingshot-z",
    "gunId": "refined-slingshot",
    "key": "Z",
    "name": "Ink Swarm",
    "version": "base",
    "mastery": null,
    "cooldown": 10.5,
    "energy": 20,
    "breaksInstinct": true,
    "description": ""
  },
  {
    "id": "refined-slingshot-x",
    "gunId": "refined-slingshot",
    "key": "X",
    "name": "Cluster Bomb",
    "version": "base",
    "mastery": null,
    "cooldown": 13.5,
    "energy": 40,
    "breaksInstinct": true,
    "description": ""
  },
  {
    "id": "skull-guitar-z",
    "gunId": "skull-guitar",
    "key": "Z",
    "name": "Soul Shaker",
    "version": "base",
    "mastery": 150,
    "cooldown": 10,
    "energy": 20,
    "breaksInstinct": false,
    "description": "The user strums the guitar and summons a skull with the power of the undead in front of them, which opens its mouth and instantly shoots a beam of souls from its mouth that can go through walls and solid surfaces, whilst inverting colors in their screens in red for a single frame."
  },
  {
    "id": "skull-guitar-x",
    "gunId": "skull-guitar",
    "key": "X",
    "name": "El Diablo",
    "version": "base",
    "mastery": 300,
    "cooldown": 14,
    "energy": 40,
    "breaksInstinct": true,
    "description": "The user quickly strums the guitar before summoning a skull, which rises to the sky with soul static, before exploding and creating an aerial laser, sending extreme energy into the core-like center, distorting the enviorment and vision of any player looking at it."
  },
  {
    "id": "slingshot-z",
    "gunId": "slingshot",
    "key": "Z",
    "name": "Ink Bomb",
    "version": "base",
    "mastery": 20,
    "cooldown": 11,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user shoots out a squid that deals damage in a small AoE range and slightly stuns the enemy."
  },
  {
    "id": "slingshot-x",
    "gunId": "slingshot",
    "key": "X",
    "name": "Proximity Bomb",
    "version": "base",
    "mastery": 40,
    "cooldown": 14,
    "energy": 40,
    "breaksInstinct": true,
    "description": "The user fires a bomb that explodes and slightly knockbacks enemies that are near it."
  },
  {
    "id": "venom-bow-z",
    "gunId": "venom-bow",
    "key": "Z",
    "name": "Venomous Spit",
    "version": "base",
    "mastery": 125,
    "cooldown": 9,
    "energy": 20,
    "breaksInstinct": true,
    "description": "The user fires 3 fast, purple projectiles from their bow. They explodes in a purple blast upon contact with an enemy or surface, and deals instantaneous damage and poison damage, breaking Instinct in one hit. Once the projectiles explode, three smaller purple arrows will come out from the explosion and chase after the nearest enemy. The arrows are very fast and hard to outrun."
  },
  {
    "id": "venom-bow-x",
    "gunId": "venom-bow",
    "key": "X",
    "name": "Serpent Bite",
    "version": "base",
    "mastery": 250,
    "cooldown": 15,
    "energy": 60,
    "breaksInstinct": false,
    "description": "The user fires multiple medium-speed purple projectiles which, upon contact with an enemy, deal some damage and stun them for a short period of time, making them unable to Flash Step, dash or use any moves (this still applies even if the enemy turns on Instinct after being hit by the move)."
  }
] as const;

export const GUN_SKILL_BY_ID: Readonly<Record<string, GunSkillDefinition>> = Object.fromEntries(GUN_SKILLS.map((s) => [s.id, s]));
